### PR TITLE
Updated headings to include a little icon.

### PR DESCRIPTION
**Pull request by pelson**
Gives the headings a little lift:

screenshot

### CODE REVIEW

**Comment by rhattersley** [comment]
Nice touch. Only downside is I keep seeing the icons as a leading “C”. How about a non-alphabetic icon?

**Comment by pelson** [comment]
> How about a non-alphabetic icon?

It is possible. I could use 
figure_1 / 
figure_1

**Comment by rhattersley** [comment]
Both look nice. Perhaps the first is more in keeping with the rest of the look'n'feel.

**Comment by ajdawson** [comment]
>Nice touch. Only downside is I keep seeing the icons as a leading “C”.

Exactly what I was thinking! I also agree that the icon without the border would probably fit better.

**Comment by pelson** [comment]
Thanks for the feedback. I've updated the PR.

**Comment by pelson** [comment]
screenshot-1

**Comment by rhattersley** [comment]
Nice. :+1: 

(If you want to be picky, I'd add a little more whitespace between the icon and the heading. But I'm OK with merging as it stands.)

**Comment by pelson** [comment]
> If you want to be picky, I'd add a little more whitespace between the icon and the heading. But I'm OK with merging as it stands

Done.

**Pull request merged**
