### PR TITLE
Port Geodesic class to pyproj

### PR DESCRIPTION
**Pull request by QuLogic**
## Rationale

The class is quite similar to pyproj's `Geod` class and can be converted almost directly. I haven't converted `trace.pyx` yet, so it gets all the definition imports moved into it. The problem for the interpolator is that it sets up a line and repeatedly finds a point in between as it bisects, whereas pyproj only supports getting these (a single point or a bunch) in one go only.

## Implications

One less dependency on compiling against Proj. See #1832

### CODE REVIEW

**Comment by QuLogic** [comment]
It might not be so difficult to port `trace.pyx` to pyproj as well, but I seem to have broken things in my first attempt.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
I'll leave it open for just a bit (unless you want to get the `trace.pyx` port here, but the tests pass and it seems straightforward enough.

**Review by greglucas — APPROVED** [review]
Looks good to me. Feel free to self-merge if you don't want to add anything else.

I don't think we can port trace.pyx over to pyproj quite yet. That will require some additions to pyproj, but we are close.

**Comment by QuLogic** [comment]
It can be done, but benchmarks show that it will increase projection times by ~50%. I don't know if this is strictly because pyproj doesn't support the `geod_line` aPI or because of the increased transitions from C code back to pyproj's Python.

**Pull request merged**
