### PR TITLE
Prepare for v0.14.0

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
Versioneer nearly got done, but I decided to keep things simple and get v0.14 out. I have no intention of taking so long to release v0.15 (in fact, if that happened in a month I'd be happy :tada:).

**Comment by pelson** [comment]
Docs have been made available at http://scitools.org.uk/cartopy/docs/v0.14/

**Comment by QuLogic** [comment]
Relatedly, have you considered getting a DOI from Zenodo?

**Comment by pelson** [comment]
> Relatedly, have you considered getting a DOI from Zenodo?

No, but not averse to the idea. Is it pretty straightforwards?

**Comment by QuLogic** [comment]
Seems so; you can even set it up to automatically create a zipball+DOI every time you make a release on GitHub.

Though if you want to have an up-to-date DOI in a readme somewhere, you'd have to first reserve a DOI, create the release with the correct DOI in the readme, then upload it to the reserved DOI. Not much more difficult I think.

**Pull request merged**
