### PR TITLE
Updated web_tiles.png image

### LINKED ISSUE #669: FAIL: cartopy.tests.mpl.test_images.test_web_tiles
The travis builds fail 
https://travis-ci.org/SciTools/cartopy/jobs/79013794#L784

### PR DESCRIPTION
**Pull request by ocefpaf**
While I was putting this PR together I noticed that plot `MapQuestOpenAerial` (`subplot(3, 2, 4)`), changed!  The image oscillated from a the current image to another one with more ice at the North Hemisphere.  Not sure if it was a one time thing or if this is not a stable tile image...

This should fix #669

### CODE REVIEW

**Comment by ocefpaf** [comment]
The tests are hanging on [test_WFSGeometrySource](https://travis-ci.org/SciTools/cartopy/jobs/80308603#L520) I think [that http://nsidc.org/cgi-bin/atlas_south?service=WFS](http://nsidc.org/cgi-bin/atlas_south?service=WFS) is down.

**Comment by pelson** [comment]
:+1:

**Comment by rhattersley** [comment]
> The image oscillated from a the current image to another one with more ice at the North Hemisphere. Not sure if it was a one time thing or if this is not a stable tile image...

In trying to back-port in #686 I'm getting an image with less ice at near the north pole (and a blob to the east of the Caspian Sea). :unamused:

**Comment by QuLogic** [comment]
Maybe it's time to stop depending on this web server...

**Comment by pelson** [comment]
> Maybe it's time to stop depending on this web server...

Indeed. Or any webserver for that matter. How much GIS background do you have @QuLogic? Is it easy to stand up a quick temporary server for WMS, WFS etc. which we can test against?

**Comment by QuLogic** [comment]
I don't know too much, but maybe pycsw would work? I guess @tomkralidis would know better.

**Comment by tomkralidis** [comment]
pycsw provides a CSW/OpenSearch/OAI/SRU endpoint.  For WMS/WFS, one could setup MapServer with some small test data to help with consistent testing.

We have the same issue in OWSLib (depending on remote services) and have discussed this in the [past](http://lists.osgeo.org/pipermail/owslib-devel/2015-March/000271.html).  Some options:

- setup a test server as part of the travis run
- setup a test server as a permanent deployment to provide WMS/WFS/WCS/CSW with small test data
- use demo servers available from existing implementations (like http://demo.mapserver.org, http://demo.pycsw.org, etc.).

**Comment by pelson** [comment]
Thanks @tomkralidis - super useful.

> use demo servers available from existing implementations (like http://demo.mapserver.org, http://demo.pycsw.org, etc.).

Interesting option. We obviously face the same risk of the results changing (our current problem), but the resilience may be healthier.

> setup a test server as part of the travis run

This is the most interesting option and the one which is most reproducible. Obviously time is the huge concern here though - if we can install and setup services in <30 seconds I think it would be a price worth paying. Much more and we would need to consider carefully how that will impact the testability.

@ocefpaf / @tomkralidis - ever done this kind of thing within travis?

**Comment by tomkralidis** [comment]
@pelson I've done it with [pycsw](https://github.com/geopython/pycsw/blob/master/.travis.yml) and we do it with [MapServer](https://github.com/mapserver/mapserver/blob/branch-7-0/run-test-suite.sh).  Test data would be required that is small enough.

**Comment by ocefpaf** [comment]
> @ocefpaf / @tomkralidis - ever done this kind of thing within travis?

Nope.  But I was going to point you to pycsw :wink:

**Pull request merged**
