### PR TITLE
Updated license headers

### PR DESCRIPTION
**Pull request by dkillick**

### CODE REVIEW

**Comment by rhattersley** [comment]
1. Travis has gone bonkers.
2. These header failures **should** have been picked up earlier by Travis. ... Double-bonkers!

**Comment by ajdawson** [comment]
The problem is the same as Iris had last year, the package installs are done individually and they keep swapping dependencies out from under one-another. E.g in the Python 2.7 build matplotlib etc are installed, but then the install of pillow swaps out the libpng version for a different one, and so on. The solution for iris was to create a requirements file and install from that.

**Comment by ajdawson** [comment]
And for license header tests, doesn't the test suite need to be run from the git repository? Looks like the tests are always run from a different directory against the installed version, so the license header check will fail.

**Comment by ajdawson** [comment]
>so the license header check will fail.

I don't mean fail, I mean "function correctly"...

**Pull request merged**
