### PR TITLE
Scipy-sphinx-theme docs 

### PR DESCRIPTION
**Pull request by corinnebosley**
This is an example of how the docs could look if we used scipy-sphinx-theme to format them.  I understand that it's not our traditional (and a little dreary...) style, but I think it is fresh and contemporary.

Needs work, obviously, but I would really appreciate opinions and input on this.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@pelson CircleCI is on this now right?  And that builds the docs? How do I look at them then?

**Comment by pelson** [comment]
It is, but I think they might be having issues with their service... it is extremely slow to load a page. I was going to look at https://circleci.com/gh/SciTools/cartopy to find the appropriate build.

To be completely honest, in order to make such a drastic change, I'd want a pretty compelling reason. Whilst a re-design would potentially have big benefit for new users, it takes mental effort for every single existing user if we change the style of the docs, and that is a cost we need to be careful to minimise.

**Comment by corinnebosley** [comment]
@pelson I disagree about mental effort for existing users.  I understand that we might want to find some sort of middle ground so that it's not too alarming, but personally I find the docs as they are now incredibly difficult to read, understand and navigate.

I don't intend to change the structure of the docs (yet...!) because that's a huge job and I expect I'll annoy a lot of people if I do, but I think we need to make our documentation user-friendly and aesthetically relaxing, and that's what this theme does.

Also, I think we need to sell ourselves a bit.  We do a lot of work on our software updating and releasing new version, and yet the docs look old and tired, and a little embarrassing to be frank.

There is scope to dial the changes back a bit by changing the conf.py in scipy-sphinx-theme, so I might play with that a bit when I get time and see what we can do with it.  Watch this space...

**Comment by QuLogic** [comment]
@pelson forgot to flip the switch to build PRs on CircleCI. I've done that now, so your next push will hopefully have docs built.

**Comment by QuLogic** [comment]
A close and open should trigger it.

**Comment by pelson** [comment]
Closing for now, as there is nothing to be reviewed yet.
Please feel free to re-open when appropriate.

Thanks 👍

**Pull request closed without merging**
