### PR TITLE
ENH: Support proj4 v5+

### LINKED ISSUE #1045: Support Proj > 4
So it looks like Proj has now released [5.0](http://lists.maptools.org/pipermail/proj/2018-March/008098.html) While they haven't broken anything *yet*, the announcement does indicate they will be breaking things in over the next couple of years. I'm opening this as a reminder to keep an eye on this and see when we may want to adapt to those changes.

### LINKED ISSUE #1071: Test failure with Proj v5.0.1
### Description

I'm working to update the cartopy package in debian.
I encountered some problem trying to run the unit tests.

The issue seems to be related to some kind of incompatibility with PROJ v5.0.1 used to build the package.
See also https://github.com/OSGeo/proj.4/issues/985.

Related issue #1045.

#### Code to reproduce

```
$ python2.7 -m pytest --pyargs cartopy.tests.crs cartopy.tests.test_crs cartopy.tests.test_geodesic
```

#### Traceback 

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
rootdir: /home/antonio/debian/git/build-area/python-cartopy-0.16.0+dfsg1, inifile:
collected 77 items

cartopy/tests/crs/test_albers_equal_area.py ......                       [  7%]
cartopy/tests/crs/test_azimuthal_equidistant.py ........                 [ 18%]
cartopy/tests/crs/test_geostationary.py ....                             [ 23%]
cartopy/tests/crs/test_lambert_azimuthal_equal_area.py ...               [ 27%]
cartopy/tests/crs/test_lambert_conformal.py ........                     [ 37%]
cartopy/tests/crs/test_mercator.py .....                                 [ 44%]
cartopy/tests/crs/test_nearside_perspective.py ....                      [ 49%]
cartopy/tests/crs/test_robinson.py ..                                    [ 51%]
cartopy/tests/crs/test_rotated_geodetic.py .                             [ 53%]
cartopy/tests/crs/test_rotated_pole.py .                                 [ 54%]
cartopy/tests/crs/test_sinusoidal.py ....                                [ 59%]
cartopy/tests/crs/test_stereographic.py .....                            [ 66%]
cartopy/tests/crs/test_transverse_mercator.py .....F.                    [ 75%]
cartopy/tests/test_crs.py ...s.........                                  [ 92%]
cartopy/tests/test_geodesic.py ......                                    [100%]

=================================== FAILURES ===================================
____________________________ TestOSNI.test_default _____________________________

self = <cartopy.tests.crs.test_transverse_mercator.TestOSNI object at 0x7fb53d7f3410>

    def test_default(self):
        proj = ccrs.OSNI()
        res = proj.transform_point(*self.point_a, src_crs=self.src_crs)
        np.testing.assert_array_almost_equal(res, (275614.87105610,
>                                                  386984.15347340))
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       (mismatch 100.0%)
E        x: array([275614.267627, 386984.20643 ])
E        y: array([275614.871056, 386984.153473])

cartopy/tests/crs/test_transverse_mercator.py:101: AssertionError
================ 1 failed, 75 passed, 1 skipped in 0.41 seconds ================
```

### Operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```

### Cartopy version

0.16.0

### LINKED ISSUE #1097: Error specifying center long for Mercator projection and extents on Python 3.6
### Description

The following code works in Python 2 but fails in Python 3. The commented lines appear to work OK however, so it is really only a minor problem.

#### Code to reproduce
```python
import cartopy.crs as ccrs
import cartopy
import matplotlib.pyplot as plt

cm_lon=51.15
maplimits = [-26., 128.3, -73.3, -31.1]

ax = plt.axes(projection=ccrs.Mercator(central_longitude=cm_lon))
#ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=cm_lon))
#ax = plt.axes(projection=ccrs.Mercator())
ax.set_extent([maplimits[0], maplimits[1], maplimits[2], maplimits[3]])
plt.show()
```

#### Traceback 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda2/envs/xesmf/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py in set_extent(self, extents, crs)
    686             # the projection extents, so try and give a better error message.
--> 687             x1, y1, x2, y2 = projected.bounds
    688         except ValueError:

ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-47cd62a8a14f> in <module>()
     12 ax.add_feature(cartopy.feature.LAND, color='gray')
     13 ax.coastlines(resolution='10m', linewidth=0.25)
---> 14 ax.set_extent([maplimits[0], maplimits[1], maplimits[2], maplimits[3]])
     15 plt.show()

~/miniconda2/envs/xesmf/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py in set_extent(self, extents, crs)
    692                    'y_limits=[{ylim[0]}, {ylim[1]}]).')
    693             raise ValueError(msg.format(xlim=self.projection.x_limits,
--> 694                                         ylim=self.projection.y_limits))
    695         self.set_xlim([x1, x2])
    696         self.set_ylim([y1, y2])

ValueError: Failed to determine the required bounds in projection coordinates. Check that the values provided are within the valid range (x_limits=[-20037508.342789244, -20037508.34278924], y_limits=[-15496570.739723722, 18764656.23138057]).

```

### PR DESCRIPTION
**Pull request by QuLogic**
~~There doesn't seem to be any problems using it, but let's see what CI says.~~

There are a couple of improvements to projections, so that requires a couple test updates.

For projections with a `central_longitude` option, one of the boundaries will now be wrapped. So we have to fuzz that one a bit by subtracting a small epsilon. I tried using `+over` originally, as suggested in the upstream ticket OSGeo/proj.4#1135, but that caused _everything_ to not wrap, so I went with the epsilon instead. It's not exactly symmetric, but only differs in the tenth of a millimetre, so probably not noticeable on a plot.

Fixes #1045.
Fixes #1071.
Fixes #1097.

### CODE REVIEW

**Comment by QuLogic** [comment]
Oops, didn't try will 5.2 yet; will fix up then.

**Comment by QuLogic** [comment]
This is now working on both old and latest proj.4; see updated description for details.

**Comment by dopplershift** [comment]
So according to the devs:
> Hence we have decided to decouple the name from the version number and from this version and onwards the product will simply be called PROJ.

Should the mentions of the library in this PR then *not* be Proj4?

**Comment by QuLogic** [comment]
Yes, that is true. I've renamed all the safe places to drop the superfluous 4. Code will have to remain the same, and I think if we want to do that, it can be in a separate PR with relevant deprecations and the like.

**Comment by dopplershift** [comment]
Yeah. I was only talking about ones added in this PR really, but cool to clean up more.

**Comment by QuLogic** [comment]
Oh right; we should commit more things so I don't have to remember this 3/4 of the way into a year.

**Comment by QuLogic** [comment]
This should now cover all issues of the 5.y.z line from conda-forge.

**Pull request merged**
