### PR TITLE
Fix incorrect units for latitude/longitude label padding

### PR DESCRIPTION
**Pull request by lukelbd**
## Rationale

In cartopy v0.18, the longitude and latitude label padding `Gridliner.xpadding` and `Gridliner.ypadding` parameters are interpreted as *dots* rather than points.

This appears to have been an accidental regression -- the developer may not have understood the difference between these two units. "Dots" are pixels on the screen, dependent on `rcParams['figure.dpi']` and the backend, while "points" are 1/72 inches.

The `rcParams['xtick.major.pad']` and `rcParams['ytick.major.pad']` settings used as default values for `xpadding` and `ypadding` have units points, so it is clear "points" are the intended units.

This one-line PR reverts back to the previous behavior. 

## Implications

In cartopy v0.18, longitude and latitude labels are unexpectedly close to the map boundary when `rcParams['figure.dpi']` is set to higher than 72ppi. And when `rcParams['savefig.dpi']` is larger than `rcParams['figure.dpi']`, this results in surprising behavior where the gridline labels are much closer to the edge when *saved* compared to what you see in the backend.

With this PR, this is no longer an issue.

### CODE REVIEW

**Comment by QuLogic** [comment]
Makes sense, but this breaks the tests that use it.

**Comment by lukelbd** [comment]
It appears only the image comparison tests failed. Could it be that the "correct" images are slightly wrong because the padding is incorrect? How can I address that?

**Comment by QuLogic** [comment]
You'd have to run the test and replace the image, or instead change the test to use different padding that's equivalent to the old version so you wouldn't have to update it.

**Comment by lukelbd** [comment]
I replaced the 4 baseline images that failed the tests (they were all gridline label tests) with the images produced in `cartopy_test_output` on my branch, but now travis is showing a different, pretty bizarre error message.

**Comment by greglucas** [comment]
It looks like those images are still failing to me. I wonder if you have some other global settings overriding something locally for you?

I updated the images on my fork if you want to try grabbing those images (passing locally for me):
https://github.com/greglucas/cartopy/tree/luke-lbd-padding-fix

I'm also not sure if we want to include your commit with vimsession in .gitignore... I am indifferent, but also feel like that should probably be in each individual user's global gitignore?

**Comment by stefraynaud** [comment]
@lukelbd, make sure that all gridliner tests pass when you install an environment equivalent to the ones used by travis.

**Comment by lukelbd** [comment]
The tests are all passing locally for me, both on my branch and on the master branch (which is updated from upstream). They just fail when I push. I have no local `matplotlibrc` settings -- I just added a single `backend: agg` line to match the travis environment settings, which prevented a fifth (unrelated) test from failing.

Do you guys have formal/online instructions for setting up a local testing environment? That could be really useful. I tried installing the packages listed in `.travis.yml` in a separate conda environment but I get unsatisfiable conflict errors.

I'll try copying files from @greglucas 's branch too.

**Comment by lukelbd** [comment]
That didn't work either. Pretty frustrating since this is just a one-line PR :/

**Comment by greglucas** [comment]
I feel for you on this :/ and completely agree that the testing system can be fickle. Sorry for the pain! The images pass the 3.6 build with the latest MPL, so the images are good on (somewhat) recent versions of everything. The 3.5 build is with MPL 1.5.1, so my guess is that there is something that changed between MPL releases having to do with padding.

We also need to start testing against more recent Python versions too...

**Comment by lukelbd** [comment]
Didn't notice the "latest everything" tests passed, I guess that's a step in the right direction. Since the images on your fork worked, could you also try running on the 1.5.1 build at some point?

FWIW I tried to make the matplotlib 1.5 environment with:

```bash
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels conda-forge/label/testing
conda config --set restore_free_channel true
conda create -n cartopy-dev python=3.5 cython=0.28 numpy=1.10.0 matplotlib=1.5.1 nose proj4=4.9.1 scipy=0.16.0 libgfortran=1 owslib=0.19.1 pillow pytest pytest-xdist filelock pep8 pyshp shapely six requests pyepsg owslib
```

but this gives me the error:

```bash
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - libgfortran=1

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/label/testing/osx-64
  - https://conda.anaconda.org/conda-forge/label/testing/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
```

And my `.condarc` looks like this:

```yaml
always_yes: true
show_channel_urls: true
auto_update_conda: true
channels:
  - conda-forge/label/testing
  - conda-forge
  - defaults
create_default_packages:
  - pip
  - ipykernel
auto_activate_base: false
restore_free_channel: true
```

Changing the order of channels did not help.

**Comment by stefraynaud** [comment]
I haven't been able to install the environment for mpl151 either.
I agree with you @lukelbd that indications are needed on how to build all testing environment, or better yet a real developer's guide.
And it's even worse when you play with texts (labels) in figures.

**Comment by lukelbd** [comment]
Looks like I got it to work :).

I successfully installed the environment by omitting the `libgfortran=1` line, and then ran the tests as shown below, moving the 3 failing test result images to the baseline image directory.

```bash
# Create environment
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels conda-forge/label/testing
conda config --set restore_free_channel true
conda create -n cartopy-dev python=3.5 cython=0.28 numpy=1.10.0 matplotlib=1.5.1 nose proj4=4.9.1 scipy=0.16.0 owslib=0.19.1 pillow pytest pytest-xdist filelock pep8 pyshp shapely six requests pyepsg owslib

# Install local cartopy copy
conda activate cartopy-dev
pip install -e .

# Run tests
pytest --pyargs cartopy
```

**Comment by lukelbd** [comment]
Also just to drive home that this PR is correct (replacing the baseline images is kind of a bold move), here is an example of the current behavior on the master branch:

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import rcParams
rcParams['figure.dpi'] = 100
rcParams['savefig.dpi'] = 1000
fig, ax = plt.subplots(subplot_kw=dict(projection=ccrs.PlateCarree()))
gl = ax.gridlines(draw_labels=True)
gl.xpadding = gl.ypadding = 50
ax.add_feature(cfeature.COASTLINE)
fig.savefig('example.png')
```

The screenshot (backend uses `rcParams['figure.dpi'] = 100`) looks like this:

gridlines-screenshot

The saved figure (backend uses `rcParams['savefig.dpi'] = 1000`) looks like this:

gridlines-saved

On this branch, the saved figure looks exactly like the original figure.

**Comment by lukelbd** [comment]
Anything else you guys need me to do before this is merged?

One thing to keep in mind is this merge will change the look of default gridline labels. But this is a restoration to the cartopy 0.17 behavior, which used the same default `xpadding = ypadding = 5` and correctly interpreted the units as "points":

https://github.com/SciTools/cartopy/blob/15cb9437dc92b2a7319cd9ae7876e4505a2bf7cb/lib/cartopy/mpl/gridliner.py#L249-L253

On the master branch with DPI of 100 (the matplotlib default) and the default padding:

cartopy-0 18 0 post dev28

On this branch, with the default padding, I get slightly more space:

cartopy-0 18 0 post dev32

**Comment by lukelbd** [comment]
Any reason this hasn't been merged yet? Does it need to be reviewed by someone?

**Pull request merged**
