### PR TITLE
Merge 0.11.x

### PR DESCRIPTION
**Pull request by QuLogic**
Passing tests for all, please?

### CODE REVIEW

**Comment by rhattersley** [comment]
> Passing tests for all, please?

:+1: :grin: 

The tests had stalled so I've kicked them off again.

**Comment by rhattersley** [comment]
The NSIDC WFS server is down. They have the following notice on their website:

> On Friday, 06 February 2015 from 8:00 a.m. to 5:00 p.m. (USA Mountain Time), we will be performing scheduled maintenance, which may cause temporary disruptions to our Web site, applications, and FTP. We apologize for any inconvenience this may cause you.

It'd be nice if the tests worked with offline/mock data, but that'll take a while to do so perhaps it's best to wait this one out.

**Comment by pelson** [comment]
> Passing tests for all, please?

Thanks @QuLogic!

**Comment by QuLogic** [comment]
Oh, well, that's unfortunate timing...

**Comment by pelson** [comment]
Thanks for holding fire @QuLogic.

**Pull request merged**
