### PR TITLE
SRTM3 update

### PR DESCRIPTION
**Pull request by QuLogic**
Basically, switch to the files from LPDAAC linked in #480. I believe these files are void filled, so maybe as @ajdawson said, a small tweak to the name might be warranted.

Another benefit of LPDAAC is that the files are all in a single directory and all consistently named. The previous `srtm.json` was actually broken because of some assumptions about the file names. It also carried a _lot_ of overhead from repeating the base URL so much. The new mask file is 465 times smaller.

A second change is to add a warning if no tiles are being downloaded.

### CODE REVIEW

**Comment by QuLogic** [comment]
OK, I took care of the caching issues, and deprecated the `fill_gaps` function. I'm also looking at providing the finer SRTM at 1 arc-second, but I think I'll leave that for a separate PR.

**Comment by pelson** [comment]
@QuLogic - could you add a what's new. I think other than that, this is pretty much good to go. :+1:

**Comment by QuLogic** [comment]
I felt like I had done that before, but I guess not. Added it now.

**Comment by QuLogic** [comment]
Ohh, I know; I wrote it to go with the SRTM1 update. Ah well, it's pretty close to what I wrote this time around.

**Comment by pelson** [comment]
:+1: thanks @QuLogic

**Comment by jsignell** [comment]
I have successfully used STRM3 with cartopy before. But LPDAAC seems to be unavailable now. Is there a way to switch the raster source?

**Pull request merged**
