### PR TITLE
Doc prettifier

### PR DESCRIPTION
**Pull request by corinnebosley**
This is a bit of a test run to see if it is worthwhile using scipy-sphinx-theme for our docs, and having played with it I really think we should use it across all SciTools docs.

Obviously we would have to change some things, and this is not so much a WIP as just a bit of a test.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@pp-mo @pelson @bjlittle Check this out: file:///net/home/h06/cbosley/Projects/cartopy/docs/build/html/index.html#

Will that work...?

**Comment by QuLogic** [comment]
I think we should merge #995, enable CircleCI, and then we can all see what the changes are here without having to build it ourselves.

**Comment by corinnebosley** [comment]
@QuLogic I totally agree.

**Comment by pelson** [comment]
I think this is overlapping with #987, but not certain. Either way, there is some work needed before it can be reviewed, so closing.

@corinnebosley - if you think this is still a thing, please could you rebase & re-open.

Thanks!

**Pull request closed without merging**
