### PR TITLE
Prep for a v0.13.0 release.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by QuLogic** [comment]
So I'm going to be cautious and assume the image failures are because you changed some tolerances and they will need updating.

Also, it looks like you've added a 0.15 milestone, but all those PRs are on master, so I'm not sure why they aren't going in 0.13?

**Comment by pelson** [comment]
> so I'm not sure why they aren't going in 0.13?

Simply because I'd like to avoid overloading releases. I'd be much happier releasing many times a year with smaller releases than releasing just 2-3 times / year.

**Comment by pelson** [comment]
Decided to remove the Orthographic change - it was a purely aesthetic change, and should be done a little more scientifically.

**Comment by QuLogic** [comment]
> Simply because I'd like to avoid overloading releases. I'd be much happier releasing many times a year with smaller releases than releasing just 2-3 times / year.

Yes, of course, but I was referring to the closed issues/PRs which, since you tagged from master, should already be fixed in 0.13.0.

**Comment by pelson** [comment]
Ah, I see. Yes, agreed. I confess, I have always used the milestones for things to do, not things already done, but I can certainly see what you mean. Its almost as if I want a feature which can split the milestone by things done, and things not done, and allow me to rename the things not done's milestone.

**Comment by QuLogic** [comment]
If you create the label first, you can label an arbitrary list by selecting them on the listing. Just add `is:open` to the search parameters.

**Comment by pelson** [comment]
Thanks @QuLogic - will try this next time :+1:

**Pull request merged**
