### PR TITLE
removed pep8 from test dependencies

### PR DESCRIPTION
**Pull request by corinnebosley**
Closes https://github.com/SciTools/cartopy/issues/905

### CODE REVIEW

**Comment by pp-mo** [comment]
Still to-do here : now stickler is working, remove the whole testclass `cartopy.tests.test_coding_standards.TestCodeFormat`, as that is all now done in CI not tests.

If I have it right, the idea is that now this is in CI not the test suite.  You can perform a manual check with the "flake8" command, which has its own controls in "setup.cfg".

**Comment by corinnebosley** [comment]
forgot to rebase...

**Comment by corinnebosley** [comment]
@pp-mo Could do with your eyes on this one now too please.

**Comment by pp-mo** [comment]
All looking fine,
*except* your test_coding_standards is still importing pep8, which needs to go.

If we had stickler working, it would warn about that !
(still waiting on #970)

**Comment by corinnebosley** [comment]
Oops, quite right @pp-mo, I've pulled it out now.

**Comment by pp-mo** [comment]
Also checked locally in merge with #970.
All good !

**Pull request merged**
