### PR TITLE
Fix some minor typos and style issues

### PR DESCRIPTION
**Pull request by QuLogic**
Just a few things found with codespell.

### CODE REVIEW

**Comment by QuLogic** [comment]
Also fixed a few flake8 things and some invalid escape sequences.

**Comment by ajdawson** [comment]
Should the changes to `versioneer.py` and `_version.py` be made in versioneer itself and a new version deployed for cartopy? The changes you made are small so I don't mind changing the generated files in this case, but it might not be a sustainable path.

**Comment by QuLogic** [comment]
I tried re-generating from the latest versioneer, but the version we have is already a patched one from @pelson, so it makes for a much larger change, and doesn't support the version scheme we currently have set.

**Comment by ajdawson** [comment]
>I tried re-generating from the latest versioneer, but the version we have is already a patched one from @pelson, so it makes for a much larger change, and doesn't support the version scheme we currently have set.

Something for another time then.

**Pull request merged**
