### PR TITLE
Remove support for Python 2

### PR DESCRIPTION
**Pull request by QuLogic**
## Rationale

Python 2 is quite a burden, so we'll be dropping it after the next release. Do not merge until it's out.

## Implications

No more Python 2.

### CODE REVIEW

**Comment by QuLogic** [comment]
So, coverage still seems to think that the installed version is important. It seems like only one file is hit there `cartopy/examples/__init__.py`, so if we can figure that one out, maybe the rest will all magically go away.

**Comment by greglucas** [comment]
Linking #1237 as something we should look at again with dropping Python 2 support. Pyupgrade will need to be run again since there have been a lot of changes since then.

**Comment by QuLogic** [comment]
Ah, I forgot about that PR. There are definitely some changes that could be taken from there, though I think these branches I made are for different things.

**Comment by QuLogic** [comment]
This is now mergeable since there's a 0.18.x branch.

**Pull request merged**
