### PR TITLE
Add api-token for CircleCI redirector action

### PR DESCRIPTION
**Pull request by bjlittle**
As [requested by @QuLogic](https://github.com/SciTools/cartopy/pull/2183#issuecomment-1577873467).

Created a CircleCI Personal API Token and added it to the repo GHA secrets as the `CIRCLECI_TOKEN` variable.

Hopefully, this can now be used with the [larsoner/circleci-artifacts-redirector-action](https://github.com/larsoner/circleci-artifacts-redirector-action) GHA.

### CODE REVIEW

**Comment by QuLogic** [comment]
Unfortunately, since this is an action that runs on statuses, not PRs specifically, I don't think we can see the results until it's merged.

**Review by QuLogic — APPROVED** [review]
Thanks @bjlittle!

**Comment by bjlittle** [comment]
> Unfortunately, since this is an action that runs on statuses, not PRs specifically, I don't think we can see the results until it's merged.

Yeah, I thought this was pretty much a merge then see what happens.

Thanks @QuLogic 👍

**Comment by QuLogic** [comment]
I believe it worked in #2186 already.

**Pull request merged**
