### PR TITLE
Fix list parameters passed to artists

### LINKED ISSUE #580: cartopy.mpl.feature_artist.FeatureArtist.draw does not preserve ordering for facecolors, etc
Example code: `ax.add_feature(cfeature.ShapelyFeature(shapefile.geometries(), crs, facecolors=['red','green','blue'])`

Intent: I want to assign a different color to each geometry in shapefile.geometries().  I can loop through shapefile.records().attr[] to create a list of facecolors (red/green/blue in the example above).  

However, the cartopy.mpl.feature_artist.FeatureArtist's draw() routine culls the list of geometries via `geoms = self._feature.intersecting_geometries(extent)`, and then creates a set of N paths for each geometry.

For this to work, draw() will need to select the correct `kwargs['facecolors']` for each geometry, and create `final_kwargs['facecolors'], duplicating that color for each path resulting from the geometry.

These should be handled similarly: edgecolors, linewidths, linestyles and antialiaseds

### PR DESCRIPTION
**Pull request by has2k1**
**Problem**

When artists are being drawn, the geometries outside the viewport
are removed before the drawing. The parameters that correspond to
removed geometries are left unchanged and so they are ill-matched
with the remaining geometries.

**Solution**

Keep track of which geometries are removed, and remove the
corresponding elements in the parameter values.

Fixes #580 

**Also**
- Changed the [hurricane katrina example](http://scitools.org.uk/cartopy/docs/latest/examples/hurricane_katrina.html) to reflect the changes introduced in here.

### CODE REVIEW

**Comment by has2k1** [comment]
One test failure.

```
The file header at lib/cartopy/mpl/feature_artist.py is out of date. The last commit was in 2017, but the copyright states it was 2016.
```

Can I update the date at the top of the affected file?

**Comment by QuLogic** [comment]
> Can I update the date at the top of the affected file?

You should if you changed it.

**Comment by QuLogic** [comment]
Looks like you'll also need to [sign the CLA](http://scitools.org.uk/governance.html#contributors) as well.

**Comment by QuLogic** [comment]
Ping @marqh, I think?

**Comment by has2k1** [comment]
It would be great to have tests for all feature types, but it does not look easy. Any ideas on to generate good tests? For the `ShapelyFeature` the Katrina example now touches on code introduced in this PR (it is a "test" of sorts).

Rebased and travis did not like it. Maybe it now requires #926.

**Comment by dopplershift** [comment]
Yeah, #926 fixes a lot of testing issues. @pelson ?

**Comment by pelson** [comment]
This has been a really valuable PR that has ultimately led to #1019, which is my preferred direction for finer control of the style through ```add_geometries``` (and ```add_feature``).

As such, I don't think we need this PR open any further.
The relevant thread of conversation is https://github.com/SciTools/cartopy/pull/1019#issuecomment-364004996. As discussed there, there is the potential for an extension to create a ```GeometryCollection```, but even that is probably best served in a new PR.

Thanks again for your input on this @has2k1 - it has been super useful, and I'm really pleased with the outcome, which I consider to be an extremely powerful interfaces for all sorts of purposed.

:+1:

**Pull request closed without merging**
