### PR TITLE
enable installing with PROJ 6.0.0

### PR DESCRIPTION
**Pull request by snowman2**
Addresses #1288

### CODE REVIEW

**Comment by snowman2** [comment]
Looks like it will actually install now. The test still fail, but I am not sure how you want to handle those.

**Comment by snowman2** [comment]
CLA signed.

**Comment by QuLogic** [comment]
It looks like this might need a bit more work to get tests to pass with proj6?

**Comment by snowman2** [comment]
Correct, but the scope of this PR is simply to enable installing with PROJ >= 6.0.0. 

The test results are different than previous versions due to updates in PROJ that I believe are more correct. The main question is: does cartopy want to have different expected test results based on the version? Or just to update the tests to the new version?

**Comment by dopplershift** [comment]
😱

**Comment by dopplershift** [comment]
I don't have the cycles to push out a release right now, but I will be trying to get CartoPy to a next release at the SciPy sprints next month. Help getting PRs reviewed and finished welcome.

**Comment by djhoese** [comment]
I know @dopplershift said he'll be working on this at SciPy, but has anyone else put more work in to this? I have a tutorial at SciPy that would benefit from having the CRS objects from pyproj 2.0+ but as far as I know that requires PROJ 6.0+ and my tutorial uses cartopy.

@snowman2 @dopplershift What's left to do on this? Can I help? Or is most of the trouble in the time to create a release?

**Comment by snowman2** [comment]
@djhoese if this is not in the next release yet, you could install the dependencies of cartopy with proj 6+ and do:
```
pip install git+https://github.com/snowman2/cartopy.git@5e624fe
```

**Comment by ocefpaf** [comment]
@djhoese and @snowman2 that can be hard for the attendants due to the c extensions in cartopy. Maybe we can publish the "dev" release on a conda-forge dev label. Would that help?

**Comment by djhoese** [comment]
I suppose if it is easy enough to install, but attendees have already starting installing stuff by following my instructions so maybe it is better to just wait for a full release? I can live with the older versions of pyproj and just explain what's "coming down the pipeline" if I have to.

**Comment by dopplershift** [comment]
@djhoese If it were my tutorial, I'd feel better about living with current releases, unless they're hopelessly broken. Can never be sure when volunteer-run projects will actually have enough the time to do a release.

**Comment by djhoese** [comment]
😉 @dopplershift Tell me about it. No problem. Thanks for all your work and status updates.

**Comment by hnsywangxin** [comment]
you can try add ADD_DEFINITIONS(-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1) cmakelist.txt

**Comment by dopplershift** [comment]
@hnsywangxin We don't use cmake to build, so I'm not sure how this is relevant? Also, this PR has already been merged, so I'm not sure that's adding anything.

**Comment by 2sn** [comment]
It seems to be still broken, even with the most recent version on github.

**Comment by 2sn** [comment]
```
     37 | #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
        |  ^~~~~
```

**Comment by 2sn** [comment]
it seems `pyproj` is broken and `cartopy` is broken - I wonder, is there anything systematically wrong with these projection libraries?
Do they need to be re-written from scratch for a better code basis?
They seem very large, maybe unmanageable?

**Comment by 2sn** [comment]
CFLAGS="-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H" pip3 install cartopy

**Comment by snowman2** [comment]
@2sn, these are open source projects. As such, you are welcome to contribute to improve them. That being said, pyproj 3.0.1 should work with PROJ 8. See: https://pyproj4.github.io/pyproj/stable/installation.html

**Comment by snowman2** [comment]
Changes needed to be compatible in #1140

**Comment by 2sn** [comment]
@snowman2 Found workaround, see above.  May not be new.  Installing on older OS, not all libraries may be up to date.
but, as I said, even installing from github
```
pip install git+https://github.com/snowman2/cartopy.git
```
does not fix the problems w/o the environment setting.

Thanks for your work on the project.  Seems monumental task.

**Pull request merged**
