### PR TITLE
Update image tests for matplotlib 2.1.

### PR DESCRIPTION
**Pull request by pelson**
Looks like a few tests were failing due to font differences, and others due to changes in underlying image sources.

### CODE REVIEW

**Comment by dopplershift** [comment]
Unfortunately, there are still 21 failing tests. 😭

**Comment by bjlittle** [comment]
I think we need to introduce some perceptual image hashing to ease the pain of graphical testing in `cartopy`.

I'm happy to make the approach we use in `iris` a generic first class citizen, so that we could easily add it as a dependency and use it for graphical testing. I think that it might make life slightly more bearable. 

I know of other `scitools` packages that would also benefit, and perhaps there maybe wider community appetite. 

Thoughts @pelson...

**Comment by pelson** [comment]
Yep, agreed. I considered doing the work myself instead of this PR. I don't really want to introduce a change to the tests that means we could not test with older versions of matplotlib - I'd like the thing to be additive, not substitutive.

Pulling out the machinery from Iris into its own project is the obvious next step, and I think that is something we should focus on next.

**Comment by QuLogic** [comment]
I'm not sure you want to update the barb/streamplot results before #1042, though I'm not sure which one has the greater effect.

**Comment by pelson** [comment]
OK, I'm going to take this one on the chin and merge even though the tests are failing. The reason I'm doing this is that:

a) master's tests have been failing for **way** too long 
b) I want to get masters test's working again, and there are tendrils to doing that in this PR

**Comment by pelson** [comment]
So I totally sent that last message to the wrong PR 🤣. I'm working on this PR, and decided to merge #1042 so that I can move this forwards.

**Comment by pelson** [comment]
🎉 - this brings the tests back online. I'm keen to address the testing issue once and for all in terms of truly reproducible image tests and data sources, but I'm reasonably content to address that in slower time. For now, we need to get the tests back up and passing.

cc @dopplershift if you'd care to do the honours before the weekend's sprints 😉 ?

**Comment by dopplershift** [comment]
:tada:

**Pull request merged**
