### PR TITLE
Added the styler keyword to allow on-demand / callback to determine styling of geometries in the matplotlib interface.

### LINKED ISSUE #580: cartopy.mpl.feature_artist.FeatureArtist.draw does not preserve ordering for facecolors, etc
Example code: `ax.add_feature(cfeature.ShapelyFeature(shapefile.geometries(), crs, facecolors=['red','green','blue'])`

Intent: I want to assign a different color to each geometry in shapefile.geometries().  I can loop through shapefile.records().attr[] to create a list of facecolors (red/green/blue in the example above).  

However, the cartopy.mpl.feature_artist.FeatureArtist's draw() routine culls the list of geometries via `geoms = self._feature.intersecting_geometries(extent)`, and then creates a set of N paths for each geometry.

For this to work, draw() will need to select the correct `kwargs['facecolors']` for each geometry, and create `final_kwargs['facecolors'], duplicating that color for each path resulting from the geometry.

These should be handled similarly: edgecolors, linewidths, linestyles and antialiaseds

### PR DESCRIPTION
**Pull request by pelson**
Replaces #910. Closes #580.

### CODE REVIEW

**Comment by has2k1** [comment]
callbacks make for an API difference compared to MPL, is there any specific advantage for them.

For my use case, callbacks would not work because the decisions on the parameter values happen somewhere in an elaborate pipeline before the calls to `ax.add_artist`. So `ax.add_geometries` needs to handle parameters just like Matplotlib collection artists.

**Comment by pelson** [comment]
> callbacks make for an API difference compared to MPL, is there any specific advantage for them.

It means we can style a feature that may not yet have all of the geometries to hand. For example, some features can return different geometries based on the zoom level.

> For my use case, callbacks would not work because the decisions on the parameter values happen somewhere in an elaborate pipeline before the calls to ax.add_artist

That form would still work (untested):

```
geoms = [geom1, geom2, geom3, geom4, geom5, geom6, geom7]
facecolors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']  

def color_lookup(geom):
    index = geoms.index(geom)
    return {'facecolor': facecolors[index]}

ax.add_geometries(geoms, crs, styler=color_lookup)
```

If you really dislike that solution, I'd be supportive of creating a GeometryCollection object that follows the same interface as the PathCollection one. Namely:

```
ax.add_collection(GeometryCollection([geoms], facecolors=facecolors, transform=crs))
```

But I don't want to bleed in index information into Features because they are inherently limited to a fixed number of geometries.

**Comment by has2k1** [comment]
That solution would work, but indeed it is not friendly. If I had not been aware of the underlying issue, it would be mysterious. It requires a little too much context to fully understand. Also, it is probably of little consequence (as geometry lengths tend to be small) but that lookup is `O(n^2)`, though it could be fixed with a 2nd lookup dictionary.

On the other hand, inspired by that code #910 could altered to take the index stuff out of the features, so that the fix is self contained, but having the `styler` and other parameters would make for a complicated API.

As such, a `styler` for `ax.add_features` and `GeometryCollection` for `ax.add_collection` is very good idea.

**Comment by pelson** [comment]
> Looks fine to me. @pelson you still feel good about this one?

Sure do. If you are at hand, please feel free to merge at will. I'm going to build something on top of this change now, and when I'm done I'll merge (if you haven't beaten me to it) before opening a new PR.

**Comment by pelson** [comment]
Actually, given how old the branch is, building something on top of it is a pretty bad idea, so I'm going to merge this and move on.

**Comment by pelson** [comment]
> Actually, given how old the branch is, building something on top of it is a pretty bad idea, so I'm going to merge this and move on.

🤣 - man, you're fast!

**Pull request merged**
