### PR TITLE
ENH: Support setting lat_ts for Mercator. (Fixes #728)

### LINKED ISSUE #728: Add support for latitude of true scale to Mercator
While most Mercator projections use 0 deg as the latitude of true scale (default), it is possible to modify this latitude using the "+lat_ts" parameter in Proj4.  This parameter currently isn't supported in the Mercator projection class.

### PR DESCRIPTION
**Pull request by dopplershift**
I needed this for some GINI satellite imagery over Hawaii. #728 mentions some issues about domain, but I don't see how that's actually relevant to the matter at hand.

### CODE REVIEW

**Comment by dopplershift** [comment]
Test failures come from changing the proj.4 string for Mercator (replacing `+k=1` with `+lat_ts=0.0`). I can update the tests no problem, but I'd like someone to weigh on whether that's the right way to go.

**Comment by dopplershift** [comment]
ping?

**Comment by QuLogic** [comment]
I looked at [the docs](http://proj4.org/projections/merc.html) and it seems to make sense to me. Do you still need to change the test string?

**Comment by dopplershift** [comment]
I bumped the test strings. Those pass now. There failures we're seeing now look unrelated.

**Comment by QuLogic** [comment]
Can you also add a test? I don't want it to end up like the Stereographic projection where the true scale there does nothing.

**Comment by dopplershift** [comment]
Yeah, I can pull one together tomorrow from the example I was running that necessitated this.

**Comment by dopplershift** [comment]
Added one that checks bounds when using `latitude_true_scale`. Looks like all of the relevant tests are passing.

**Comment by dopplershift** [comment]
ping?

**Comment by QuLogic** [comment]
Thanks @dopplershift!

**Pull request merged**
