### PR TITLE
Made use of versioneer.

### PR DESCRIPTION
**Pull request by pelson**
So that we don't have to do the version shuffle again. :smile:

### CODE REVIEW

**Comment by pelson** [comment]
Never again do I want to do the version shuffle: https://github.com/SciTools/cartopy/pull/761#issuecomment-212839696

**Comment by rhattersley** [comment]
This looks like a simple, generic (i.e. you've not customised the versioneer bits?) change. Can we simply do the same for iris, or are there implications?

**Comment by pelson** [comment]
> This looks like a simple, generic (i.e. you've not customised the versioneer bits?) change

I'm afraid that isn't entirely true: https://github.com/SciTools/cartopy/pull/743/files#diff-11e1c7ae2bdac6c08e2dbd2b612f9c3eR9

This is based off of my PR for versioneer which handles maintenance branches. We are in esteemed company though - matplotlib has been using it since v1.5.0 :wink:

**Comment by pelson** [comment]
Hmmm. I've just checked the matplotlib versioneer, and I must have been mistaken. It looks like a pretty vanilla versioneer there... :confused:

**Comment by QuLogic** [comment]
It looks likes it's requiring `setup.cfg`, but I thought your patched version doesn't?

**Comment by pelson** [comment]
Just found an issue with ``pip install --no-deps .`` using versioneer. Error:

```
    UPDATING (build py) build/lib.macosx-10.6-x86_64-2.7/lib/cartopy/_version.py
    error: [Errno 2] No such file or directory: 'build/lib.macosx-10.6-x86_64-2.7/lib/cartopy/_version.py'
```

It looks like the build_py override of versioneer can't handle the lib directory. I'm going to take a look at hot-fixing the version of versioneer we have.

**Comment by pelson** [comment]
> It looks like the build_py override of versioneer can't handle the lib directory. I'm going to take a look at hot-fixing the version of versioneer we have.


Doh! I think it was simply that I had setup.cfg wrong. Changing ``versionfile_build`` did the trick.

**Comment by pelson** [comment]
Have had problems with stickler here - I'm going to let that through.

Given the age of this PR, and that it will make actually cutting v0.16 easier, I'm going to merge this one myself.

**Pull request merged**
