### PR TITLE
Updated .travis.yml lto use miniconda 3.7.0

### PR DESCRIPTION
**Pull request by esc24**
`conda update conda` is breaking at the moment. May be this will fix it.

### CODE REVIEW

**Comment by ajdawson** [comment]
Looks like `conda update conda` is working OK, but the Natural Earth data issues will make this fail.

**Comment by esc24** [comment]
Any chance of merging? I can then rebase #528 to see if that helps the natural earth issue.

**Comment by ajdawson** [comment]
Slightly concerned about the way that failed... Difficult to tell what the issue is.

**Comment by pelson** [comment]
> Slightly concerned about the way that failed... Difficult to tell what the issue is.

I agree. But I'm confident that it wasn't caused by updating conda itself (though it may be that a different version of GEOS has been used or some such thing).

@esc24 - I'm not uncomfortable merging this, but wonder why v0.11.x hasn't been targeted?

**Pull request closed without merging**
