### PR TITLE
Added an example demonstrating an eccentric ellipse.

### PR DESCRIPTION
**Pull request by pelson**
figure_1

### CODE REVIEW

**Comment by pelson** [comment]
I don't propose putting this into v0.12.x - instead, I'd like to start pulling on the globe thread. Interesting discussions to be had both #330 and #564.

Does anybody listening do anything with highly eccentric ellipsoids? @ThomasLecocq / @rsignell-usgs any geological survey type applications you know of? I'd love to get a few extra terrestrial examples in the gallery...

**Comment by ThomasLecocq** [comment]
not that I know of. Probably martian/planetology guys ? I'll check

**Comment by QuLogic** [comment]
According to [this](http://en.wikipedia.org/wiki/Equatorial_bulge#Other_celestial_bodies), Saturn's the one to beat, though it's merely 1:10.21, which is not super visible.

**Comment by rhattersley** [comment]
> According to this, Saturn's the one to beat, though it's merely 1:10.21, which is not super visible.

http://en.wikipedia.org/wiki/Telesto_%28moon%29 ?

**Pull request merged**
