### PR TITLE
Initial port to proj8

### PR DESCRIPTION
**Pull request by manisandro**
This is work in progress, I'm working on it as time allowes as I need it to finish the proj-8 update in Fedora. The code compiles, but there are still many test failures which I need to investigate.

### CODE REVIEW

**Comment by QuLogic** [comment]
Originally, I would have said that we should support both, but Proj 5 is now 3 years old, so I think we can switch APIs directly, unless anyone else has any objections?

That being said, I don't think the new API should break anything, so these test failures will probably need to be figured out first.

**Comment by dopplershift** [comment]
I agree with @QuLogic on both accounts.

**Comment by QuLogic** [comment]
@manisandro are you able to continue on this?

**Comment by manisandro** [comment]
@QuLogic Currently I don't have any time to work on this

**Comment by QuLogic** [comment]
Can you sign the CLA so we can use this?

**Comment by QuLogic** [comment]
Replaced by #1808.

**Pull request closed without merging**
