### PR TITLE
Add MPL trove classifier

### PR DESCRIPTION
**Pull request by pharshalp**
## Rationale

Matplotlib got its own trove classifier!

## Implications
Adding this classifier would help with discoverability of cartopy.
See: https://github.com/pypa/pypi-support/issues/232

### CODE REVIEW

**Comment by pharshalp** [comment]
CLA signed

**Comment by QuLogic** [comment]
Please can you keep the list sorted?

**Comment by pharshalp** [comment]
> 
> 
> Please can you keep the list sorted?

done.

**Comment by QuLogic** [comment]
Thanks @pharshalp!

**Pull request merged**
