### PR TITLE
Add disk caching to GSHHSFeature

### PR DESCRIPTION
**Pull request by stefraynaud**
## Rationale

In-memory caching already exists for some features, which improves the  loading of all features for a given set of parameters.  However, it still take alot of time to get high resolution features, even in a limited area; and this is often what happens for people working in regional and coastal regions.
So, I already did for basemap, I implemented a similar disk caching for the GSHHSFeature only (for the moment). The cache file names are based on scale, level and extent. This is no caching when the extent parameter is not passed. All geometries that intersect this bbox are cached. Config options have been added for that:

- allow_disk_caching: set to False by default (for the moment)
- cache_dir: like data_dir
- max_cache_usage: in MB.

Here a minimal script that test performances:

````python
from __future__ import print_function
from cartopy.feature import GSHHSFeature
from time import time
from cPickle import dump, load

x1 = -5.5
x2 = -4.5
y1 = 48
y2 = 49

extent = x1, x2, y1, y2

print('EXTENT:', extent)
for scale in ('c', 'l', 'i', 'h', 'f'):
    print('SCALE:', scale)

    t0 = time()
    GSHHSFeature._geometries_cache = {}
    gshhs = GSHHSFeature(scale=scale)
    print('  Init: {:.2f}s'.format(time() - t0))

    t0 = time()
    geoms = list(gshhs.intersecting_geometries(extent))
    print('  Loading of full shapefile: {:.2f}s'.format(time() - t0))

    t0 = time()
    geoms = list(gshhs.intersecting_geometries(extent))
    print('  Just clipping: {:.2f}s'.format(time() - t0))

    cfile =__file__[:-2] + 'pyk'
    with open(cfile, 'w') as f:
        dump(geoms, f)

    t0 = time()
    with open(cfile) as f:
        geoms2 = load(f)
    print('  From pyk file: {:.2f}s'.format(time() - t0))

````
Here are the outputs:

````
EXTENT: (-5.5, -4.5, 48, 49)
SCALE: c
  Init: 0.00s
  Loading of full shapefile: 0.45s
  Just clipping: 0.02s
  From pyk file: 0.01s
SCALE: l
  Init: 0.01s
  Loading of full shapefile: 1.89s
  Just clipping: 0.06s
  From pyk file: 0.04s
SCALE: i
  Init: 0.04s
  Loading of full shapefile: 7.46s
  Just clipping: 0.56s
  From pyk file: 0.21s
SCALE: h
  Init: 0.21s
  Loading of full shapefile: 15.28s
  Just clipping: 0.64s
  From pyk file: 0.29s
SCALE: f
  Init: 0.37s
  Loading of full shapefile: 39.07s
  Just clipping: 2.35s
  From pyk file: 4.37s
````

## Implications

This will help regional and coastal users to efficiently use cartopy.

## Checklist

- [ x] If you have not already done so, ensure you've read and signed the Contributor Licence Agreement (CLA).  (See the [governance page](http://scitools.org.uk/governance.html) for the CLA and what to do with it).
- [x] Ensure there is a suitable item in the cartopy test suite for the change you are proposing.

### CODE REVIEW

**Comment by stefraynaud** [comment]
I sent the CLA.

**Comment by stefraynaud** [comment]
This solves #1110

**Comment by QuLogic** [comment]
Looks like this needs a rebase.

**Comment by pelson** [comment]
@stefraynaud - taking a big step back here, the way GSHHS is currently architected is a little bit awkward IMO. We do not take advantage of the fact that tools like Fiona allow us to do a bounding box extract directly from the file (and *really* fast). Before implementing caching of an awkward implementation, I'd like to discount the possibility of improving the implementation at its core.

The hooks I'd be looking at are keeping a Fiona handle open until we destroy the GSHHS object and implementing ``source.filter(bbox=...)`` in the ``intersecting_geometries`` method. Would you be interested in exploring this option - it would have potentially huge savings at startup, though may have a slightly higher overhead for each subsequent iteration (though potentially not even there, as shapely wouldn't be involved in doing the intersectioning).

**Pull request closed without merging**
