### PR TITLE
Update dependency to pyshp v2.1.1 to correctly display shapefiles with multi-polygon holes

### PR DESCRIPTION
**Pull request by karimbahgat**
## Rationale

The new v0.18 introduced problems with rendering some shapefiles (#1578). This was due to how the pyshp dependency converted the internal shapefile shape structure to GeoJSON for multipolygons with holes, sometimes assigning the holes to the wrong polygon. A new version of PyShp has since fixed this issue, including several other shapefile bug fixes, and this PR updates the dependency to use the newest PyShp version. The PR also cleans up some of the code that uses pyshp. 

## Implications

This bugfix PR will make it a requirement for all cartopy users to upgrade their pyshp version to >= v2.1.1, in order to ensure that all Cartopy users get the correct rendering (#1578). I'm not sure to what degree requiring such an upgrade is a nuisance, or if the added benefit is sufficient for such a change. 

As part of cleaning up the code that uses pyshp, I also removed the io.shapereader.Record's `fields` argument and private `._fields` attribute, as this did not seem to be used anywhere else in the codebase, and shouldn't have any benefit, since the record's fieldnames are already stored as the keys to the `attributes` dict. Anything that relies on this seemingly unused `fields` arg/attr would break, but I see no reason why anyone would need it and the attribute is private anyway.

### CODE REVIEW

**Comment by greglucas** [comment]
We are currently following [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) with a 24-month dependency policy. See issue https://github.com/SciTools/cartopy/issues/1518 for discussion around that.

Can the hard dependency be removed and just allow users to benefit if they upgrade pyshp themselves? That being said, I think all of the refactors are good, and we probably need a deprecation for the fields keyword in case someone downstream is using that even though we aren't.

**Comment by dopplershift** [comment]
I like the clean-ups as well. Are they compatible with pyshp < 2? I think that's another consideration for what version of `pyshp` we support here.

**Comment by karimbahgat** [comment]
Good point @greglucas, does requiring a newer version constitute a dependency break? If cartopy was to require it, would that mean inserting a deprecation warning and then adding the version bump requirement after 24 months? Maybe it would be best to just leave this as an optional benefit for those that have the newer version. I think it depends how serious you think issue #1578 is, if it's an acceptable Cartopy bug for those with the older pyshp versions? As I point out in [pyshp issue 202](https://github.com/GeospatialPython/pyshp/issues/202), the bug is only potentially relevant for multipolygons with holes, and even then I believe most of the time the polygon rings are ordered in the way assumed by the code, not resulting in the reported error, though I cannot be certain. 

@dopplershift, some of the code cleanup would not in fact be compatible with pyshp < 2, specifically len(shapefile) and .as_dict(), so I would have to redo those differently if you don't want to require pyshp 2+. Then I should probably also make a new PR, that only focuses on the code refactoring.

**Comment by karimbahgat** [comment]
Also, iterShapes and iterShapeRecords apparently were only available since pyshp 1.2.2, which would break in some cases since cartopy requires only pyshp>=1.1.4. So most of the code refactoring depends what is done regarding version requirement. Ultimately I would say the code refactoring is less important, more important is whether or not to upgrade pyshp. Not sure when v1.1.4 is from, but v1.1.7 is from back in 2013. At least at some point an upgrade should be considered, there are plenty of bug fixes as well as read efficiency improvements.

**Comment by greglucas** [comment]
Looking at the analysis of https://github.com/SciTools/cartopy/issues/1518 again, the 24-month dependency rule would put pyshp at 2.0.0. So, my vote would be to update the requirements file to require `pyshp >= 2` and take advantage of all your refactors here. In fact, all of the minimum requirements in the requirements file are not even currently tested, so I have no idea if numpy 1.10 would even work anymore honestly.

**Comment by karimbahgat** [comment]
Ok, just to get some closure on this, I think the PR should be ready for merging now, if everyone agrees on the version issue. I changed so the dependency only require pyshp 2 or bigger, and I undid removing the fields arg, as that should probably be another PR and needs a deprecation warning.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Looks good. Thanks @karimbahgat !

**Pull request merged**
