### PR TITLE
Update Natural Earth URL

### PR DESCRIPTION
**Pull request by rcomer**
This is my first Cartopy PR, so apologies if I've missed something!

## Rationale

Updated the URL for Natural Earth feature downloads, following the AWS template provided by @acarapetis at https://github.com/SciTools/cartopy/issues/1325#issuecomment-904343657.  @greglucas stated at https://github.com/SciTools/cartopy/issues/1325#issuecomment-904686853 that he thinks AWS is the official replacement for the https://naciscdn.org/ source (which has been rather intermittent in recent weeks).

## Implications

Hopefully the shapefile downloads will become a bit more reliable.

### CODE REVIEW

**Comment by rcomer** [comment]
Tested locally by running one of the gallery examples, and got a warning that suggested the files were indeed coming from the new location.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Looks good to me!

**Comment by rcomer** [comment]
Thanks @dopplershift!

**Comment by emrodalmeida** [comment]
I've updated cartopy to 0.19.0 and it worked locally, but it is still trying to download the shapefiles from the old url when I execute the scripit within a Jupyter notebook with Binder. Please, am I missing something?

**Comment by dopplershift** [comment]
Did you download the updated copy of the script from [this repo](https://raw.githubusercontent.com/SciTools/cartopy/master/tools/cartopy_feature_download.py)?

**Comment by emrodalmeida** [comment]
No, I haven't because the installation of version 0.19.0 through conda-forge had worked locally. For the remote execution I specified this version in the environment.yml file in my github repo. This exceeds my Python knowledge, thus could you please explain how this script should be used when remotely running cartopy in a jupyter notebook?

**Comment by ktyle** [comment]
I just tested and downloading is working great from AWS using the updated shapereader.py script.

**Comment by dopplershift** [comment]
Honestly, it sounds like the best solution is to get the Binder to regenerate the Docker image it's using with the latest cartopy from conda-forge, which has been patched to use the updated URL. You *may* also be able to trigger this inside a notebook with `!conda update -c conda-forge cartopy`.

**Comment by jdldeauna** [comment]
Hi! I've been trying to use the `regionmask` package and running into a similar problem with the Natural Earth URL. I tried installing cartopy with `!conda update -c conda-forge --yes cartopy` but this gives me `v=0.18.0`. I tried doing: `!conda install -c conda-forge --yes cartopy=0.19.0`, but it's been approx ~1hr and it still hasn't installed which is unusually long. I'm doing the installation on a Cloud server but I'm not sure that makes a difference since it installed just fine when I didn't specify a version number. Would appreciate any tips, thanks!

**Comment by rcomer** [comment]
@jdldeauna I have no expertise on this, but there was a suggestion at https://github.com/SciTools/cartopy/issues/1846#issuecomment-915548993 to try

`conda install -c conda-forge cartopy=0.19.0.post1 `

**Comment by emrodalmeida** [comment]
Folks, here is something that worked for me:

At first I was explicitly requesting the dependence of version 0.19.0 in my environment.yml, just I've done in my local environment, which was working fine. This version was installed in the image created by the docker as expected, but the script was still trying to download from the old url. However, when the command `!conda install -c conda-forge -y cartopy=0.19.0` was executed from a cell code it actually installed the version 0.19.0.post1, which is downloading the shapefiles from the new url and is working correctly. Thus, I just modified the environment.yml dependence to request version 0.19.0.post1 and got the problem solved.

I can't say if it was an issue with the conda-forge channel for cartopy or if it was some bug with the docker image, but I think that this version discrepance between those from the explicit dependence and the installation through conda may be the cause of malfunction related by the other users as well.

Thank you all for your support!

**Comment by jdldeauna** [comment]
Thanks for the helpful tips!

**Pull request merged**
