### PR TITLE
A fix on the filename for the shapefile Reader. 

### PR DESCRIPTION
**Pull request by jolivetr**
## Rationale

Shapefile from nature_earth could not be read. Additional Kwargs were added for some reason while they were conflicting with pyshp. 

## Implications

It should work now...

### CODE REVIEW

**Review by greglucas — CHANGES_REQUESTED** [review]
Do you have a reproducible example that was failing before this and what this is fixing? It would help to have a little bit more context of why this is needed since none of our CIs are currently failing and it doesn't look like pyshp has updated anything recently.

I'm also not sure we are guaranteed to get passed in a `Path` object, but could instead get a string filename directly which would cause the `.suffix` call to error.

**Comment by jolivetr** [comment]
Well, simply the example on the gallery https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/features.html#sphx-glr-gallery-lines-and-polygons-features-py <https://scitools.org.uk/cartopy/docs/latest/gallery/lines_and_polygons/features.html#sphx-glr-gallery-lines-and-polygons-features-py> fails.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:343, in BaseFormatter.__call__(self, obj)
    341 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:341>     pass
    342 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:342> else:
--> 343 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:343>     return printer(obj)
    344 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:344> # Finally look for special method names
    345 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/formatters.py:345> method = get_real_method(obj, self.print_method)

File /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:170, in print_figure(fig, fmt, bbox_inches, base64, **kwargs)
    167 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:167>     from matplotlib.backend_bases import FigureCanvasBase
    168 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:168>     FigureCanvasBase(fig)
--> 170 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:170> fig.canvas.print_figure(bytes_io, **kw)
    171 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:171> data = bytes_io.getvalue()
    172 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/pylabtools.py:172> if fmt == 'svg':

File /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2164, in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2161 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2161>     # we do this instead of `self.figure.draw_without_rendering`
   2162 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2162>     # so that we can inject the orientation
   2163 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2163>     with getattr(renderer, "_draw_disabled", nullcontext)():
-> 2164 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2164>         self.figure.draw(renderer)
   2165 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2165> if bbox_inches:
   2166 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py:2166>     if bbox_inches == "tight":

File /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/artist.py:95, in _finalize_rasterization.<locals>.draw_wrapper(artist, renderer, *args, **kwargs)
...
--> 144 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cartopy/io/shapereader.py:144>     raise ValueError("Incomplete shapefile definition "
    145 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cartopy/io/shapereader.py:145>                      "in '%s'." % filename)
    147 <https://file+.vscode-resource.vscode-cdn.net/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cartopy/io/shapereader.py:147> self._fields = self._reader.fields

ValueError: Incomplete shapefile definition in '/Users/romainjolivet/.local/share/cartopy/shapefiles/natural_earth/physical/ne_110m_land.shp'.

The shapefile is simply not passed correctly.
R

—————————————————————————————————————
—————————————————————————————————————	
Romain Jolivet
Professeur des universités — Professor

Département de Géosciences
École Normale Supérieure
24 rue Lhomond
75005 Paris
France

email: ***@***.***
Work: +33 1 44 32 22 04
—————————————————————————————————————
—————————————————————————————————————

**Comment by rcomer** [comment]
The gallery examples get run within our CI.  This was most recently done about an hour ago with no problems.  I suspect there may be a problem with your local copy of the shapefile.  I suggest deleting the shapefile directory and trying again.

**Comment by dopplershift** [comment]
Do we have jobs that span both fiona and pyshp (e.g. no fiona) configurations for the gallery examples?

**Comment by rcomer** [comment]
> Do we have jobs that span both fiona and pyshp (e.g. no fiona) configurations for the gallery examples?

Good point - probably not.  However I have a local environment with pyshp 2.3.1 and no fiona, and I get no error with that example.  I am using Conda on Ubuntu.

**Comment by jolivetr** [comment]
I am using macports on a M1 apple computer running OS12 Monterey (port py312-cartopy @0.23)

Removing the shapefiles from the .local directory leads to the same issue. 

Tracking this down, I realized that cartopy was passing a file with a .shp suffix and that pyshp does not accept filenames with a suffix.
Hence the quick fix that I proposed. I was also surprised to see a posix name provided, and I agree a str would be simpler and more general. 

Maybe I could add a condition (if the file ends with .shp, then remove it) but that’s not very clean and it does not explain why my case fails while yours work (I did not try conda on my mac, but with a manually compiled version of python on our cluster, it fails as well with the same error). 
 
—————————————————————————————————————
—————————————————————————————————————	
Romain Jolivet
Professeur des universités — Professor

Département de Géosciences
École Normale Supérieure
24 rue Lhomond
75005 Paris
France

email: ***@***.***
Work: +33 1 44 32 22 04
—————————————————————————————————————
—————————————————————————————————————

**Comment by greglucas** [comment]
I am also unable to reproduce this. There must be something with your environment.

Installing `pyshp` into a fresh virtual environment and testing that directly without Cartopy involved.

```python
>>> import shapefile
>>> from pathlib import Path
>>> p = Path(".local/share/cartopy/shapefiles/natural_earth/physical/ne_110m_coastline.shp")
>>> shapefile.Reader(p)
<shapefile.Reader object at 0x101533f10>
```

demonstrates that it works as expected for me. This may be an issue you need to raise with pyshp and not Cartopy. Can you isolate it to just pyshp? What is your version of pyshp?

**Comment by jolivetr** [comment]
Ok, this is because the pyshp port of macports is out of date… 
I was running version 2.1.3 (latest available on macports) and force install the 2.3.1 with pip did the job.
A lot of python ports are out-of-date at macports, including numpy and scipy, and that starts to be annoying.
Thanks a lot for the help and sorry for the trouble

—————————————————————————————————————
—————————————————————————————————————	
Romain Jolivet
Professeur des universités — Professor

Département de Géosciences
École Normale Supérieure
24 rue Lhomond
75005 Paris
France

email: ***@***.***
Work: +33 1 44 32 22 04
—————————————————————————————————————
—————————————————————————————————————

**Comment by QuLogic** [comment]
Yes, we require `pyshp` 2.3 or later: https://github.com/SciTools/cartopy/blob/v0.23.0/pyproject.toml#L53

Perhaps consider using micromamba/conda-forge instead of macports.

**Pull request closed without merging**
