### PR TITLE
Preparations for the new v5 SciTools CLA

### PR DESCRIPTION
**Pull request by trexfeathers**
## Rationale

Reference the upcoming new [SciTools Contributor Licence Agreement (v5)](https://cla-assistant.io/SciTools/), which is being implemented to comply with legal advice from the UK Met Office - see https://github.com/SciTools/cartopy/issues/1919#issuecomment-1679258852 .

I have chosen to no longer link to scitools.org.uk, since the new CLA is designed to be 'self-describing' without needing other exposition, hence the new Summary section at the top.

This is has been set up - via [CLA Assistant](https://cla-assistant.io/) - in most SciTools repositories on `2023-12-22`. Cartopy has been exempted to allow time for people to see and discuss. We could add further documentation, and even altering the CLA's summary text would be OK at this point because very few people would need to re-sign.

## Implications

All pull request authors will be automatically asked to sign the CLA as part of the continuous integration checks. An example of such a check is here: https://github.com/SciTools-incubator/iris-esmf-regrid/pull/239#issuecomment-1781422917 .

The intention is to apply a branch protection rule that prevents merges to `main` unless all commit authors have signed the CLA, achieved by checking for a ✔ from this CI check.

### CODE REVIEW

**Comment by trexfeathers** [comment]
ping @SciTools/cartopy-devs

**Comment by rcomer** [comment]
Does #2285 need to be merged before this?

**Comment by trexfeathers** [comment]
> Does #2285 need to be merged before this?

They are only related in a conceptual sense. Neither references the other, and @lbdreyer has already put in the heroics to get approval for re-licensing from the existing authors, so we're not dependent on the new CLA for permission to do that.

**Review by greglucas — APPROVED** [review]

**Review by dopplershift — APPROVED** [review]
Seems good to me. I'll leave this open for others to review.

**Review by bjlittle — APPROVED** [review]

**Pull request merged**
