### PR TITLE
Use proj geodesic functions for spherical interpolation.

### PR DESCRIPTION
**Pull request by QuLogic**
## Rationale

These are more accurate (though unlikely visible at plotting scales), and handle some more corner cases.

## Implications

Basically what it says above. Also, the less code we maintain ourselves, the better...

### CODE REVIEW

**Comment by dopplershift** [comment]
So looks like we need to bump the minimum Proj version for this. Not sure when we want to do that.

**Comment by QuLogic** [comment]
Oh, hmm, well, geodesic lines should still be there; might be able to still get it working with some checks.

**Comment by pelson** [comment]
@QuLogic - how did performance compare? I could imagine it going either way, but that original geodesics code was pretty slim-line.

**Comment by QuLogic** [comment]
I could not see any appreciable difference on the test suite, though it's pretty quick already; maybe some pathological cases would be different.

**Pull request merged**
