### PR TITLE
Add support for SRTM with 1 arc-second resolution.

### PR DESCRIPTION
**Pull request by QuLogic**
The LP DAAC provides SRTM at 3 and 1 arc-second resolution. This PR adds support for the 1 arc-second dataset.

### CODE REVIEW

**Comment by pelson** [comment]
```
The file header at lib/cartopy/io/srtm.py is out of date. The last commit was in 2016, but the copyright states it was 2015.
```

It would also be great if we could get a unit test. It doesn't necessarily need to download anything, but would be great to know it was getting the right files...

**Comment by pelson** [comment]
Once that is done :+1:

As a follow on activity, I'd love to see a what's new entry, and a gallery addition, if you're interested?

**Comment by QuLogic** [comment]
Ah yes, I forgot about the tests. About the, can they made more generative? I don't really want to repeat all the SRTM3 tests just to make the SRTM1 ones.

I did add a what's new entry; the gallery entry might just be a small addition to the existing one.

**Comment by QuLogic** [comment]
OK, tests were no so difficult in the end. In the example, it seems like SRTM1 is just a bit noisier version of SRTM3...

**Comment by pelson** [comment]
I suspect we can be smarter about the gallery examples, but I don't think that needs to be done in this PR. Eventually, I'd like to see the two datasets showing off different domains, so that we can see the benefits of SRTM1 vs 3.

Great work @QuLogic!

**Pull request merged**
