### PR TITLE
Egs 2 gallery

### PR DESCRIPTION
**Pull request by pp-mo**
Addresses #991.
Does the same thing for inline code in the 'gridlines' documentation.

### CODE REVIEW

**Comment by QuLogic** [comment]
What is egs? I'll also note that you don't need to create anchors manually; sphinx-gallery adds one for every example, see [the getting started page](https://sphinx-gallery.github.io/getting_started.html#know-your-gallery-files)

**Comment by pp-mo** [comment]
> What is egs? 

Examples, as, in "e.g.".
I don't think I used that anywhere in the codebase ?


> you don't need to create anchors manually

Thanks, I'll check that out.  As usual, I was boilerplating (?verb?) from something I found elsewhere.

**Comment by pp-mo** [comment]
> you don't need to create anchors manually

A much more serious matter is the test failures, due to the example code intoducing dependencies on netCDF4 and iris (!arrgh!).  We surely don't want to add Iris to the test dependencies, so I may need to revert that

.. or work out how to stop pytest loading the examples? 
I *think* this occurs because "pytest --doctest-modules" attempts to import everything it can find.
But I'm not too clear why, as I think we don't actually ***have*** any doctests.
**Anyone know about that  ?**

**Comment by pp-mo** [comment]
> test failures ... we don't actually have any doctests.

From offline discussion with @pelson , we absolutely *do* have doctests, and in his opinion (now also mine :wink:) we shouldn't *either* stop running doctests *or* restrict what we put in examples just to fix this.
Instead, to keep CI speed up, we should probably do this as part of a CI docs-build.
That could be via #995 -- or if that causes problems maybe an additional travis matrix element ?

I'm going to close this PR until one of those provides a better way to expand examples dependencies.

**Pull request closed without merging**
