### PR TITLE
Update coding standards

### PR DESCRIPTION
**Pull request by pelson**
## Rationale

The test_coding_standards test now reflects https://github.com/SciTools/scitools.org.uk/pull/209 without needing a wholesale change to all files in the cartopy codebase.

Specifically the year does not need to be part of the header, and the full license details can be referenced rather than explicit.

## Implications

 * We don't have to jump through hoops to set the year when we change a file (because the year isn't part of the license header preamble anymore). Users who really want this information can reference the repository at GitHub.
 * We don't have to include all of the terms of the license in the preamble, it is sufficient to reference a file in the repository.
 * Completely empty files (e.g. ``__init__.py``) no longer need a license header **nor** the special future imports tested for in test_coding_standards.

TODO:

 * [x] https://github.com/SciTools/scitools.org.uk/pull/209 needs to be merged
 * [x] A LICENSE file needs to be added to the cartopy repository root

### CODE REVIEW

**Comment by pelson** [comment]
No more pre-amble year updates 🎉. Rather than add a commit that changes *every single file* I suggest we update these as we go, which means we will see failures as we update files, but we won't be obliged to to this annually.

**Comment by dopplershift** [comment]
🎉

**Comment by greglucas** [comment]
I was just going through some people's PRs and noticed that a lot of CI failures were because of the copyright header year not being updated. It looks like from the discussion above,

> Specifically the year does not need to be part of the header, and the full license details can be referenced rather than explicit.

does this imply that the year in each source file isn't needed, but rather just a reference to the main LICENSE file in the base of the repo?

I also noticed that the updates here removed the Crown Copyright and changed it to Cartopy Contributors, but all of the source files still contain the Crown Copyright. I'm wondering if this should all be updated in the main LICENSE file to something along the lines of Crown Copyright 2011 - 2018, Cartopy Contributors 2019 - 2020 indicating when you made the switch?

This is all to say that I have no experience with legal-speak, and am just looking to avoid only finding the copyright failure on CI when all other checks have passed locally.
Another option that I haven't looked at is to see if there is a way to put `test_coding_standards.py` copyright year checks into pytest somehow so that people could see the failures when they run the test suite locally.

**Comment by QuLogic** [comment]
I believe both headers are allowed (see the license header test) to allow for piecemeal conversion. It just hasn't really been done on most files.

`test_coding_standards` is already triggered by pytest, but you need to be in the git directory.

**Comment by greglucas** [comment]
Thanks, @QuLogic! I must have been doing something funky in my directory to not be running it. I see it is getting called in pytest for me locally now.

**Comment by pelson** [comment]
> I believe both headers are allowed (see the license header test) to allow for piecemeal conversion. It just hasn't really been done on most files.

I was going to wait until Jan 2020 to get rid of the years altogether, but turned out things got a bit busy 😄 

From a LICENSE file perspective, technically we can say that all of the contributions to cartopy are copyright "Cartopy contributors". To be explicit, I recommend all future updates to the headers remove years as supported by this PR so that we never have this silly situation where we are making unnecessary commits because of some arbitrary date.

**Pull request merged**
