### PR TITLE
modified the geos version check procedure to omit version string comp…

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
Modified the GEOS version check procedure to omit version string components with the word 'dev' from the tuple

Old behavior:
```
import sys
import os
import subprocess
>>> geos_version = subprocess.check_output(['geos-config', '--version'])
>>> print(geos_version) # my check
>>> geos_version = tuple(int(v) for v in geos_version.split(b'.')) 
b'3.8.0dev\n'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <genexpr>
ValueError: invalid literal for int() with base 10: b'0dev\n'

```
Result from modification
```
>>> geos_version = subprocess.check_output(['geos-config', '--version'])
>>> geos_version = tuple(int(v) for v in geos_version.split(b'.') if 'dev' not in str(v))
>>> print(geos_version
(3, 8)
```

## Rationale

This modification permits the user to build Cartopy with up-to-date GEOS code that contains 'dev' in the version string (i.e., code from the [master branch](https://git.osgeo.org/gitea/geos/geos/src/branch/master)).

### CODE REVIEW

**Comment by dopplershift** [comment]
Seems sensible to me. Can you sign the [electronic CLA form](https://docs.google.com/forms/d/e/1FAIpQLSfd0tdE-DcJOXh8ej_7T93IizwJFYBFyRWYQOi2A8QRaKwykA/viewform)?

**Comment by wrongkindofdoctor** [comment]
Ryan,

Thanks for accepting the changes. I signed the CLA form before I made the pull request, and have attached a copy if you need it for reference.

-Jessica

-------- Original Message --------

**Comment by QuLogic** [comment]
Can you rebase to get working tests?

Also, did you sign the electronic form, or the old PDF?

**Comment by wrongkindofdoctor** [comment]
I've signed the new electronic form, and rebased my changes onto the master branch.

**Comment by QuLogic** [comment]
Is the email on the commits right? The CLA check doesn't identify you, because GitHub doesn't recognize you as the author.

**Comment by wrongkindofdoctor** [comment]
Yup--I entered the wrong email.I resubmitted the CLA form with the correct information, so hopefully the check passes this time around.

**Comment by QuLogic** [comment]
Sorry, I meant the emails on the commits. As you can see, GitHub doesn't have your profile pic on them because it doesn't recognize the email as yours.

**Comment by wrongkindofdoctor** [comment]
Ah, that's because I set the user.email field to a blank string for privacy. I solved the problem by amending the commit messages with the masked github email address, and submitted a new CLA form with the masked address.

**Comment by QuLogic** [comment]
Thanks! And sorry for the complications.

**Pull request merged**
