### PR TITLE
Update v0.15.x

### PR DESCRIPTION
**Pull request by dkillick**
Sucks a couple of bugfixes onto v0.15.x, where they should have been merged to originally. I feel some dev notes on bugfixes and releases coming on...

Changes:

 * add `lon_0` argument to Gnomic projection.
 * add OSGB to native SRS' for WMS/WMTS retrieval.

### CODE REVIEW

**Comment by ajdawson** [comment]
> where they should have been merged to originally

Neither of these are really bug fixes are they?

> add lon_0 argument to Gnomic projection.

This isn't at least (actually it is an API break, but let's not get into that).

**Comment by dkillick** [comment]
Maybe they aren't bug fixes, but they aren't breaking changes either. In fact, I think it is easier to argue the Gnomic change is a bugfix because it is correcting a part of the API **that should have been there in the first place**.

Pragmatically, they're both tiny fixes that _people need_. Shall we tell them they're going to have to wait three months for us to do a proper release?

**Comment by ajdawson** [comment]
Well, I hope it won't be 3 months until 0.16, but that's probably another discussion! I just wanted to make sure you were aware that the Gnomic change could break existing code, so you can make sure you have considered that properly before putting it in a bugfix release.

**Comment by dkillick** [comment]
> that's probably another discussion

Quite...

> you were aware that the Gnomic change could break existing code

We had discussed this. If the were adding a new arg I wouldn't even consider it but given it adds a kwarg I'm not as concerned as kwargs are very opt-in.

**Comment by ajdawson** [comment]
Specifically, things that look like this will be broken by this change:

```python
central_latitude = 55.0
globe = ccrs.Globe(...)

proj = Gnomic(central_latitude, globe)
```

because the `globe` argument will now be interpreted as a central longitude (and fail).

**Comment by dkillick** [comment]
Ah, the globe. Alright, can I at least release my change?

**Comment by ajdawson** [comment]
You can do whatever you like, I'm not here to forbid you from doing this, I just wanted to make sure the decision had been fully considered.

Your change looks extremely innocent, I can't think of a way it will break anything.

**Comment by dkillick** [comment]
>  I just wanted to make sure the decision had been fully considered

Which it evidently hadn't :scream: Thanks @ajdawson!

**Pull request closed without merging**
