### PR TITLE
Merge v0.12.x

### PR DESCRIPTION
**Pull request by QuLogic**
Many bug fixes...
The version's probably going to conflict, though.

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @QuLogic. I've merged by hand.

**Comment by ajdawson** [comment]
You deleted the v0.12.x branch?

**Comment by pelson** [comment]
> You deleted the v0.12.x branch?

:fire: argh! Thanks @ajdawson :fire_engine:... sometimes github's interface is too friendly!

**Comment by ajdawson** [comment]
Ha ha, at least there is also an undo button!

**Pull request merged**
