### PR TITLE
Add Stamen Toner and Watercolor image tiles

### PR DESCRIPTION
**Pull request by manugarri**
This simple PR adds the two other versions of static map tiles that Stamen adds.

Basically I modified the `StamenTerrain` to access the different endpoints for the Toner maps (`http://tile.stamen.com/toner/`) and Watercolor (`http://tile.stamen.com/watercolor/`)

### CODE REVIEW

**Comment by manugarri** [comment]
```Become a Contributor with any of the tasks described above. Please note that merging of source code contributions is at the discretion of the Developers and follows an iterative dialogue. We will also need a completed Contributor's Licence Agreement (CLA). Please read the Privacy Policy to understand how we will use any personal data we collect about you.```

Hey guys, I just wanted to help with a quick fix, but it seems there is a lot of bureaucracy to collaborate with this project.

**Comment by ajdawson** [comment]
Thanks for contributing, we're always happy to have new contributors.

>Hey guys, I just wanted to help with a quick fix, but it seems there is a lot of bureaucracy to collaborate with this project

Just a single electronic CLA form to complete: http://scitools.org.uk/documents/cla_form.pdf. Once you fill it in and email to the specified address we can add you to the contributors list and you can submit as many PRs as you like without any more form filling bureaucracy! If you are unsure about CLAs the following is a reasonable overview: http://oss-watch.ac.uk/resources/cla

**Comment by manugarri** [comment]
@ajdawson sent

**Comment by manugarri** [comment]
@pelson I sent the CLA agreement last week :)

**Comment by manugarri** [comment]
@pelson  not sure what the next steps are , I sent the signed CLA as instructed by @ajdawson but thew CI is still failling with " CLA doesn't exist for all commits (authors: manugarri) "

**Comment by pelson** [comment]
Yep, I'm going through the process of getting the CLA through the door 😄  (not much to it really). Nothing on your side needed. Sorry about the delay.

**Comment by manugarri** [comment]
oh great! Let me know if there is anything else required :)

**Comment by QuLogic** [comment]
I think you should add either links, or a cross-reference to the `StamenTerrain` class, for more context.

**Comment by manugarri** [comment]
@QuLogic I did not want to interfere with the current api.

**Comment by QuLogic** [comment]
I don't understand; I'm talking about the docstrings.

**Comment by manugarri** [comment]
@QuLogic ooh that would make sense. Given how the StamenTerrain docstring only provides a description of the map tiles, can you provide a link to the official Stamen Toner/Watercolor Description? As far as I can tell, these Stamen maps don't have an official description.

**Comment by manugarri** [comment]
@pelson any update on this?

**Comment by dopplershift** [comment]
I think you need to address the comments by @QuLogic and improve the docstrings. Specifically:
1. Cross-reference to the `StamenTerrain` class for the details behind the tiles (":class:\`StamenTerrain`" in sphinx)
2. Link to http://maps.stamen.com/
3. Add a bit more text describing what they are (i.e. toner is black and white, watercolor is...)

**Comment by QuLogic** [comment]
Ping @manugarri?

**Comment by pelson** [comment]
I reviewed this in #1188. Moving the work over to that PR.

**Comment by manugarri** [comment]
My apologies @QuLogic , been completely disconnected from this project.

**Comment by pelson** [comment]
@manugarri - we've all been there - me more than most! 🤣
Your presence is really welcome anytime - what can be more fun than making maps!? 😉

**Pull request closed without merging**
