### PR TITLE
Use higher default zorder for unfilled Features

### PR DESCRIPTION
**Pull request by QuLogic**
This matches the behaviour of contours in Matplotlib, where unfilled vs filled have different default zorder.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, alas, it breaks more than I expected because Matplotlib <3.5 still does the weird sorting.

**Review by greglucas — COMMENTED** [review]
I think this may be a bit too fancy? Setting the zorder to 1.5 as a default is pretty simple and self-explanatory, and then the user can go and adjust it from there, IMO. They won't have to think about whether the Feature they added was a patch or a line.

I like this location of updating the zorder though, so I changed the other PR to update `self.set_zorder(1.5)` in the default case.

**Comment by dopplershift** [comment]
Would it be better to wait for this until we drop matplotlib <3.5?

**Comment by greglucas** [comment]
The reason for this change is that many of the coastlines disappear from the tests with MPL 3.5, which would likely mess up a lot of people's scripts. The change in MPL 3.5 would cause a difference in order depending on:
```python
ax.coastlines()
ax.contourf()
```
vs
```python
ax.contourf()
ax.coastlines()
```
because the default zorder of the two situations are the same. Previously, "artists" of the same zorder would still get sorted after everything else. That is no longer the case and all artists of the same zorder get sorted by when they were added to the list.

**Comment by QuLogic** [comment]
This re-orders a bunch of things with older Matplotlib, so let's go with your PR instead.

**Pull request closed without merging**
