### PR TITLE
change hemisphere location i gridlines labels.

### PR DESCRIPTION
**Pull request by emsterr**
change hemisphere location i gridlines labels. The hemisphere is now moved to the end of the label text, instead of after the degree symbol. (12°N34'45" -> 12°34'45"N)

Discussed in Issue #1671 

## Rationale
The usual presentation of degrees, minutes, seconds  is with hemisphere at the end of the text.

### CODE REVIEW

**Review by greglucas — APPROVED** [review]
Looks good to me. I'm going to approve and leave it up for a bit in case anyone else has an opinion that this needs a deprecation notice. I'd rather just fix it and not add bloat with more keywords though, so this gets my vote.

**Comment by greglucas** [comment]
@emsterr, it looks like there are some merge conflicts, can you rebase this onto the latest master to update the labels?

**Comment by emsterr** [comment]
@greglucas, I will merge it in and verify.

**Comment by emsterr** [comment]
Hello @greglucas, I have been away for some weeks, but will continue where i left of. If I need to hurry due to new release, just let me know.

**Review by greglucas — APPROVED** [review]
Looks good to me. It'd be good to get one more approval since this is actually breaking what was done, but I think it is worth it to change the strings without any deprecation dance since I couldn't find anywhere else that style was used.

**Comment by greglucas** [comment]
Thanks, @emsterr! I think this is the most accepted formatting, so a good change to the defaults.

**Pull request merged**
