### PR TITLE
Bump to v0.14.1

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by QuLogic** [comment]
Uh, the tag of 0.14.1 is not on here, but on some earlier dev version.

**Comment by QuLogic** [comment]
Ping again?

**Comment by pelson** [comment]
Thanks @QuLogic. Have I tagged master instead of v0.14.x maybe? Ok, let's just tag v0.14.2 and we can kill two birds with one stone :wink: 

P.S. Sorry about the slowness - my notifications have gone crazy with conda-forge.

**Comment by QuLogic** [comment]
> Have I tagged master instead of v0.14.x maybe?

Yes, that looks pretty likely to be the reason. I guess we should merge back at some point.

**Pull request merged**
