### PR TITLE
Make sure we run tests with fiona

### PR DESCRIPTION
**Pull request by dopplershift**
We're failing shape reader tests when we use fiona. Step 1, make sure we catch it with CI. From there, we'll see.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, the pinning problem is that Proj4 is now 4.9.3 here.

**Comment by dopplershift** [comment]
Looks like we can get this in now that #1210 is in.

**Comment by dopplershift** [comment]
GDAL on conda-forge hasn't been rebuilt with Proj 5.2. See conda-forge/gdal-feedstock#237.

Any reason this needs to wait on that?

**Comment by dopplershift** [comment]
Rebased.

**Comment by QuLogic** [comment]
And conveniently, the other build was done so now it's running proj 5.2.0 on both latest builds.

**Comment by dopplershift** [comment]
I actually don't understand how using 5.2.0 is possible, but ok.

**Comment by pelson** [comment]
I feel like this has just moved the problem. The issue is the if statement in https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/shapereader.py#L248 which basically changes the behaviour if Fiona is installed or not. How about instead we do some pytest magic to ensure we trigger both cases for all shapereader *specific* tests?

Does something like the following have the desired effect do you think?  (untested):

```
@pytest.fixture(params=['fiona', 'pyshp'])
def shapereader_implementation(request):
    if request.param == 'fiona' and not _HAS_FIONA:
        pytest.skip('test required fiona')
    if request.param == 'pyshp':
        target = cartopy.io.shapereader.BasicReader
    else:
        target = cartopy.io.shapereader.FionaReader
    with mock.patch('cartopy.io.shapereader.Reader', target): 
         yield
```

And then appropriate tests using this fixture.

I've no attachment to the code above - it was a hack to demonstrate the concept. I'm very keen to ensure we have test coverage of both pyshp and fiona even if we have an installation of fiona.

**Comment by dopplershift** [comment]
That seems entirely reasonable to me. I just wanted to get something in that ensured we had at least *some* coverage of it. Because we were able to make a release that failed tests, at least under certain conditions.

**Pull request merged**
