### PR TITLE
V0.20.x

### PR DESCRIPTION
**Pull request by yaswant**
## Rationale

addresses issue #2017 

## Implications
None

### CODE REVIEW

**Comment by dopplershift** [comment]
I'm still on the fence whether we should ship these files, but I'm a definite -1 on including it in the git repository (they do occasionally change). If we do ship them, my preference would be to add the download as a build-time step for generating the wheels and the source distribution in `setup.py`.

**Review by greglucas — CHANGES_REQUESTED** [review]
Yes, I am against putting these into the git repository as well.

I think documentation could go a long way here. There are some good suggestions for how to handle the offline data access in this issue: https://github.com/SciTools/cartopy/issues/1325 that could be brought out into a documentation page to explain the options clearly.

Another thought would be to add a timeout to the download so it doesn't just hang on a system without internet access, but then someone on a poor internet connection will probably complain because the timeout isn't long enough...

Also as a note here is that this only includes the 110m resolution coastlines, but the `ax.coastlines()` call actually adds an auto-scaling feature, so if you're on a limited-extent region it would try to grab `10m` or `50m` coastline features and you'd be back in the same predicament...

**Comment by yaswant** [comment]
@dopplershift , @greglucas  thanks for your comments.  I am not in favour or against including the files in git repo.  Cartopy does include an older version of GSHHS files though, and once can use `GeoAxes.add_feature` method to use them.  So why is it okay to have GSHHS files?  I can see the point when this can still fail (limited extent) - thanks for highlighting that.

We have software stacks deployed on production and hpc systems which are not connected to the world.  There, the coastlines method fails out-of-the-box, which I personally think is not desirable.  I'll take a look at #1325

**Comment by dopplershift** [comment]
@yaswant Well I wasn't around when those data were included, but would have argued against it since it's an external, updated dataset. For instance, the copy in the repo is from 2009, while the official source has renamed to [gshhg](https://www.soest.hawaii.edu/pwessel/gshhg/) and was last updated in 2017.

I'm definitely game to better support use of cartopy in environments without network use. I just think better options are either making it easier to let users dump them in the right spot (or point cartopy to where they already exist), or to only grab them when building packages.

**Comment by yaswant** [comment]
@dopplershift that was my point too.  Recognizing this inconsistence and in anticipation of a reasonable fix, I am closing this PR, but keeping the issue open.

**Pull request closed without merging**
