### PR TITLE
Remove redundant Python 2 code

### PR DESCRIPTION
**Pull request by hugovk**
## Rationale

New version of https://github.com/SciTools/cartopy/pull/1237.

Python 2 is no longer supported, remove redundant code.

Add "Programming Language :: Python :: 3 :: Only" Trove classifier for clarity.

Fixes https://github.com/SciTools/cartopy/issues/1186.

## Implications

Python 2 is no longer supported.

### CODE REVIEW

**Comment by QuLogic** [comment]
Probably want to leave out the header changes for #1539.

**Comment by hugovk** [comment]
The CI failed without the copyright year changes.

Should I ignore those? Or remove the check? Or wait for something else to be merged first?

**Comment by QuLogic** [comment]
Better to wait for #1539 which will remove those lines entirely.

**Comment by greglucas** [comment]
I just merged in that other PR. This will need a rebase now.

**Comment by hugovk** [comment]
Updated and rebased!

**Comment by greglucas** [comment]
Thanks @hugovk!

**Pull request merged**
