### PR TITLE
adds update boundary example

### PR DESCRIPTION
**Pull request by digitalvapor**
example by @pelson in https://github.com/SciTools/cartopy/issues/527

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @digitalvapor - I was thinking of making the function a method on the GeoAxes and thus hiding the user from some of the implementation details.

One thing I didn't check was whether it is possible to define the patch in a coordinate system which is not transData - that would allow us to natively define a box in lat lon which is automatically transformed to the coordinate system of the map. 
It may be that this is a little too much to ask for though - matplotlib does make a few assumptions about transforms and transData...

**Comment by pelson** [comment]
P.S. Before this can be merged, would you mind sending over a CLS as per https://github.com/SciTools/cartopy/blob/master/CONTRIBUTING.md.

**Comment by digitalvapor** [comment]
I filled it out, but I don't really see an easy to send option for the CLA, but that all sounds agreeable. Instead of pdf, is there just an electronic form? I release all rights to my contribution if that eases this. It would be nice if you were able to write a disclaimer in the readme that if you contribute then you are agreeing to the CLA then less paperwork for everyone.

**Comment by pelson** [comment]
> It would be nice if you were able to write a disclaimer in the readme that if you contribute then you are agreeing to the CLA then less paperwork for everyone.

It would be nice if a CLA wasn't needed at all... :wink: 

>  Instead of pdf, is there just an electronic form?
You should be able to fill the PDF in in Acroread and send it off to the email address at the top of http://scitools.org.uk/documents/cla_form.pdf.

Let me know if that is causing a hassle though - I don't want this to put you off contributing! 

Cheers,

**Comment by digitalvapor** [comment]
Ha yeah. I sent it over.

**Comment by pelson** [comment]
@digitalvapor - I'm looking to push a pretty important fix into cartopy in the next few weeks, and will probably want to do a new release as a result (ping @SciTools/cartopy-devs), so this would be an awesome addition to the gallery for then. Is there any chance you will have the bandwidth to take a look?

Cheers!

**Comment by pelson** [comment]
Replaced by #559.

**Pull request closed without merging**
