### PR TITLE
DOC: Adding release notes for v0.19

### PR DESCRIPTION
**Pull request by greglucas**
Updating the whats_new page in the documentation with the new contributions/features.

Below is a list of things that, in my opinion, would be good to have a review/merge of before release if possible. If anyone else wants to add anything critical, mention the issue/PR in the comments and I'll add it in.

## Should go in before release

- [ ] Bugfix for pcolormesh interpolation (#1646)

## Would be nice
- [ ] Rename feature download and include it in release (#1602)
- [ ] Rework of gridliner and labels (#1537, #1538)
- [ ] Faster contouring (#1690)

### CODE REVIEW

**Comment by smartlixx** [comment]
It would be good to add some examples in the new release to showcase some of the major improvements, e.g., the further improvement of the gridliner and the animation capability.

**Comment by greglucas** [comment]
Thanks for the suggestions @smartlixx!

The gridliner work isn't in yet, so I haven't added that. If you want to review any of the PRs from the list to help them along that would be great too!

**Comment by greglucas** [comment]
There is really not much left on the milestones at this point.
https://github.com/SciTools/cartopy/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.19

I think we should aim for a release in the next week (or two) if possible. Many of the issues/PRs in the backlog are not urgent, but there are some bug fixes that were planned for v0.18.1 that never got released that would be nice to get out the door. Please ping me if anyone wants a review on anything before the release.

**Comment by adamgarbo** [comment]
Very much looking forward to #1537 and #1538 and would be keen to see these included in the 0.19 release. Happy to test any of the proposed changes!

**Comment by greglucas** [comment]
@adamgarbo, feel free to comment on those PRs. I think there was still an open discussion around how to set the x/y + top/bottom labels. If you have a preference for any of the proposed methods, it'd be great to hear your perspective over on that thread.

**Comment by greglucas** [comment]
It seems like no one has complained about the release candidate (no idea how much testing there has even been) and there hasn't been any progress on the other PRs, so I think we are ready for a release.

We still need to update the date of the release in the docs before tagging.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
I'm leaving unmerged if you want to go ahead and update the date. Otherwise, feel fee to self-merge.

**Comment by greglucas** [comment]
Well, I was going to tag tonight, but the WMTS docs are failing, so I'll wait until I can deploy both simultaneously. I'm pretty sure this is an issue upstream somewhere, but I'm not sure where. This is just over the past few days and it doesn't look like owslib has had a release since February, so I'm thinking it may be the NASA tile service...?

Relevant error:
```
Unexpected failing examples:
/root/project/examples/web_services/reprojected_wmts.py failed leaving traceback:
Traceback (most recent call last):
  File "/root/project/examples/web_services/reprojected_wmts.py", line 54, in <module>
    plot_city_lights()
  File "/root/project/examples/web_services/reprojected_wmts.py", line 40, in plot_city_lights
    ax.add_wmts(base_uri, layer_name=layer_name)
  File "/root/project/lib/cartopy/mpl/geoaxes.py", line 2140, in add_wmts
    gettile_extra_kwargs=wmts_kwargs)
  File "/root/project/lib/cartopy/io/ogc_clients.py", line 356, in __init__
    wmts = owslib.wmts.WebMapTileService(wmts)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 189, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 240, in _buildMetadata
    gather_layers(caps, None)
  File "/opt/conda/envs/test-environment/lib/python3.7/site-packages/owslib/wmts.py", line 237, in gather_layers
    'already exists' % cm.id)
KeyError: 'Content metadata for layer "AMSUA_NOAA15_Brightness_Temp_Channel_10" already exists'
```

**Comment by greglucas** [comment]
I forgot that we had flagged the known failing WMTS examples in the past as well. I think that may be the best path forward here for now. The 0.19 docs will not have those examples, but I don't think that should hold up the release because it requires an upstream fix.

Let me know if you agree with this, or if anyone wants to keep waiting.

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Thanks for pushing this through @greglucas !

**Pull request merged**
