### PR TITLE
update matplotlib canonical.

### PR DESCRIPTION
**Pull request by jklymak**
See https://discourse.matplotlib.org/t/canonical-documentation-have-moved/21863

### CODE REVIEW

**Comment by greglucas** [comment]
Can you sign the CLA?
https://docs.google.com/forms/d/e/1FAIpQLSfd0tdE-DcJOXh8ej_7T93IizwJFYBFyRWYQOi2A8QRaKwykA/viewform

**Comment by jklymak** [comment]
I did so far as I know.  Or feel free to put in a parallel pr.  Thanks.

**Comment by greglucas** [comment]
@SciTools/developers is there a place to check that the CLA is signed? I thought the blocking bot gets removed automatically upon submission.

**Comment by rcomer** [comment]
We have documentation on the CLA here:
https://github.com/SciTools/scitools.org.uk/wiki/Contributors-License-Agreement-processing-details#where-can-i-see-a-list-of-all-of-those-that-have-signed-the-cla

But I only know this thanks to the discussion here:
https://github.com/SciTools/scitools.org.uk/issues/232

@jklymak is on the list 👍

**Comment by greglucas** [comment]
🤦  I didn't think of checking the website repository...

Thanks @rcomer!

**Pull request merged**
