### PR TITLE
bug fix relating to issue #945 raised on 2 Nov 2017. Needed to modify…

### PR DESCRIPTION
**Pull request by scaine1**
… intersecting_geometries in Feature class. It was not possible to use rivers_lake_centerlines dataset from NaturalEarthFeature at scales of 10m or 50m without this fix

### CODE REVIEW

**Comment by scaine1** [comment]
Contributor Licence Agreement sent on Dec 8

**Comment by ajdawson** [comment]
Looks good to me.

The CLA has been received and processed. However, the commits were made with an email address that is not known to your Github account, so Github doesn't know they belong to @scaine1. You can remedy this by adding the email address you used to make the commit to your account (settings->email), so Github knows it should associate these commits with your account.

**Comment by scaine1** [comment]
Oops silly mistake! Thanks for letting me know ajdawson.
I have now added the address used to do the commit. Does that mean I have to cancel and do another pull request or will the CLA-checker get to it automatically?

**Comment by ajdawson** [comment]
No worries, I'm happy to merge this without re-running the check. Thanks for the contribution @scaine1, much appreciated.

**Pull request merged**
