### PR TITLE
Compatibility with shapely 2.0 (remove usage of lgeos)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
The changes of https://github.com/SciTools/cartopy/pull/2080 squashed and applied to v0.21.x branch

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@greglucas any idea if the CI failures are related?

**Review by greglucas — APPROVED** [review]
Those test failures are unrelated. I am getting them locally as well. Looks like someone must have changed the XML content or parsing somewhere along the chain with those remote tests. We should really get that XML content and monkeypatch URL to not go to a remote resource when possible... But, lets not have that hold us up here.

Thanks, @jorisvandenbossche!

**Comment by greglucas** [comment]
Actually, it looks like this wasn't enough. I just checked out shapely 2.0 with the Cartopy v0.21.x branch and there are a few failures still. I am not sure it is worth the effort of doing all the backporting on v0.21.x versus just making a new minor release from main.

**Comment by jorisvandenbossche** [comment]
@greglucas which failure do you see? CI here has a build with shapely 2.0rc3, and AFAIK the only 2 failures are the unrelated ones that also happen in the other builds

**Comment by greglucas** [comment]
Uggh, I must have been looking at other Actions and didn't realize this did bring the CI over as well, sorry for the noise! I created a new environment locally and now all is working as expected (with the two unrelated tests failing).

I just pushed a release from this branch, so people should be able to use the new Cartopy and Shapely releases together now.

**Comment by jorisvandenbossche** [comment]
Great! Thanks a lot!

**Pull request merged**
