### PR TITLE
Default lonlat formatter

### PR DESCRIPTION
**Pull request by stefraynaud**
## Rationale

Longitude and latitude labels have no meaning for projections other than `PlateCarree`.
However, the default label formatter is always of longitude and latitude degrees type, whetever the gridliner crs is.
A test is now added and the default formatter is of `ScalarFormatter` type as in MPL, except when the crs is `PlateCaree()`.

## Implications

This prevents displaying labels in degrees for projected gridlines.

### CODE REVIEW

**Comment by greglucas** [comment]
Looks good now! Can you squash the recent commits down to cleanup your history?

**Comment by stefraynaud** [comment]
It tried to squash commit but I'm not sure it worked.

**Comment by QuLogic** [comment]
It did not. When you rebase or squash, you need to force push to overwrite the other end. Do not follow git's advice to `git pull`, because then you will end up with two copies of the commits (rebased and not).

Use `git push --force-with-lease` after rebasing.

**Comment by stefraynaud** [comment]
None of tests for squashing work. I'm missing Something somewhere.
Should I create a new PR to make things clear?

**Comment by greglucas** [comment]
Looks like you'll have to resolve some conflicts now too, unfortunately :(

I assume this is what you were trying?
```bash
# Fetch latest commits from `upstream` (the original fork)
git fetch upstream

# Get your branch
git checkout default_lonlat_formatter

# Reapply it onto upstream's master
# (use -i and pick/squash specific commits)
git rebase -i upstream/master

# Fix conflicts, then `git rebase --continue`, repeat until done
# Push to our fork
git push --force origin default_lonlat_formatter
```

I'm fine with you opening a new PR and cross-referencing this one too if none of that worked.

**Comment by dopplershift** [comment]
Closing in lieu of #1492.

**Pull request closed without merging**
