### PR TITLE
Add Eckert family of projections

### PR DESCRIPTION
**Pull request by QuLogic**
## Rationale

Requested in #1156.

## Implications

Note, this is based on #1167, because I want to avoid some result changes that it _might_ create (though I didn't really check.)

### CODE REVIEW

**Comment by QuLogic** [comment]
Here is [the Eckert family](https://732-5282596-gh.circle-artifacts.com/0/root/project/docs/build/html/crs/projections.html#eckerti) in the docs.

**Comment by QuLogic** [comment]
Oops, just realized that `Eckert*` don't support elliptical globes, so I've dropped some extra tests and added the relevant warning for incompatible globes.

**Comment by QuLogic** [comment]
Wish GitHub could figure that out automatically, but rebased.

**Comment by dopplershift** [comment]
Test failure is #1171, merging over that.

**Pull request merged**
