### PR TITLE
Add python_requires to help pip

### PR DESCRIPTION
**Pull request by hugovk**
## Rationale

When old Python versions are dropped, `python_requires` will help pip install the right version for people still running those old Python versions.
 
For more info on how this works:
* https://packaging.python.org/guides/dropping-older-python-versions/
* https://hackernoon.com/phasing-out-python-runtimes-gracefully-956f112f33c4

## Implications

If people are using an old pip (<9) or setuptools (<24), the keyword has no effect and pip will try and install the very latest release of cartopy. But in this case, it's exactly the same as not including this keyword. It's inclusion won't cause any errors.

### CODE REVIEW

**Comment by hugovk** [comment]
> In terms of supported python versions the reality is that we only have confidence with v3.5 and v3.6 (assumed v3.7).

Shall I change it to be 2.7 and 3.5+, and update the classifiers to match?
```diff
-    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*',
+    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
```

```diff
-             'Programming Language :: Python :: 3.3',
-             'Programming Language :: Python :: 3.4',
              'Programming Language :: Python :: 3.5',
+             'Programming Language :: Python :: 3.6',
+             'Programming Language :: Python :: 3.7',
```

**Comment by pelson** [comment]
@hugovk - there is a CLA process in place that you can follow, or you can trail-blaze and have a go our (as yet) unreleased CLA signing process at https://scitools.org.uk/cla/v4/form.

> Shall I change it to be 2.7 and 3.5+, and update the classifiers to match?

Sure thing. Let's say it how it is. 👍

**Comment by hugovk** [comment]
Updated, and signed!

**Comment by pelson** [comment]
> Looks good! @pelson Are we good with the CLA?

The answer is: it's complicated 😆 

We have the CLA, but not yet finished the integration with the CI here. This change doesn't really need a CLA so happy to merge anyway, but for subsequent contributions by @hugovk we need to have the CLA CI working (action on me).

**Pull request merged**
