### PR TITLE
Plotting Bathymetry shapefiles

### PR DESCRIPTION
**Pull request by mattphysics**
## Rationale

I have come across the question of how to plot ocean bathymetry in cartopy. This led me to write a short notebook of how to do that using the Shapefiles from Natural Earth. I was encouraged to share this so others can benefit.
Note that this is my first pull request on here, and I'm not sure this is exactly the right place. Please advise if appropriate.

## Implications

No implications

### CODE REVIEW

**Comment by dopplershift** [comment]
Greetings! Thanks for making the effort to contribute! Cartopy's examples don't use notebooks, but standalone Python scripts. If you'd like to have your example include (which looks great!), you'll need to convert the notebook to a script like the [others vector data examples](https://github.com/SciTools/cartopy/tree/master/examples/vector_data).

**Comment by mattphysics** [comment]
Thank you, I'll do that!

**Comment by greglucas** [comment]
@mattphysics, kind ping in case you're still interested in turning that example into a standalone script for the gallery.

**Comment by lgolston** [comment]
This can be closed as the derived version (PR #2195) is live in the gallery.

**Pull request closed without merging**
