### PR TITLE
Rename feature_download.py

### PR DESCRIPTION
**Pull request by stefraynaud**
## Rationale

Rename ` feature_download.py`  to `cartopy_feature_download.py` and add it to setup.py to make it installable.

I prefixed it with `cartopy_` to make it clear that it is a cartopy tool.

## Implications

Once cartopy is installed, the user has a direct access to ` cartopy_feature_download.py`  to install new features, without having to search for this script.

### CODE REVIEW

**Comment by greglucas** [comment]
This seems good to me too, not sure why it isn't installed already. Can you rebase to resolve the conflicts?

**Comment by QuLogic** [comment]
You'll need to update CI for the name change.

**Comment by stefraynaud** [comment]
It's ok,there now.

**Review by greglucas — APPROVED** [review]
Looks good to me.

**Pull request merged**
