### PR TITLE
Debug coveralls.

### PR DESCRIPTION
**Pull request by QuLogic**
## Rationale

Testing

### CODE REVIEW

**Comment by greglucas** [comment]
I'm wondering if most of the coverall issues are fixed now that we dropped Python 2 support?

**Comment by QuLogic** [comment]
Possibly, I see the coverage is now back up to ~80 again.

**Comment by greglucas** [comment]
Was there any other debugging you were doing with Coveralls in this PR?

**Comment by QuLogic** [comment]
Hmm, I forget, might as well close.

**Pull request closed without merging**
