### PR TITLE
MNT: Add a cache to the Transformer creation in transform_points

### LINKED ISSUE #1915: PyProj transformers often reinstantiated
Profiling an animation I've been fiddling with, I noticed about 10 seconds (~15% of the total run time) was spent in `_safe_pj_transform`:

```
         24631906 function calls (23998894 primitive calls) in 62.484 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
     4660    0.025    0.000   11.467    0.002 geoaxes.py:117(transform_non_affine)
     4660    0.407    0.000   11.441    0.002 crs.py:336(transform_points)
...
     4660    0.016    0.000   10.998    0.002 crs.py:42(_safe_pj_transform)
     4660    0.025    0.000   10.859    0.002 transformer.py:471(from_crs)
     4660    0.033    0.000   10.813    0.002 transformer.py:298(__init__)
     4660    0.009    0.000   10.764    0.002 transformer.py:91(__call__)
     4660   10.724    0.002   10.746    0.002 {pyproj._transformer.from_crs}
```

Constantly creating new `Transformer` instances seems to be quite expensive. A quick hack improves things drastically:

```
sage: import functools
sage: ccrs.Transformer.from_crs = functools.cache(ccrs.Transformer.from_crs)
sage: cProfile.run('ani.save("/tmp/test.gif")', sort=pstats.SortKey.CUMULATIVE)
         24871283 function calls (24218669 primitive calls) in 51.364 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
     4660    0.020    0.000    0.322    0.000 geoaxes.py:117(transform_non_affine)
...
     4660    0.147    0.000    0.301    0.000 crs.py:336(transform_points)
...
     4660    0.019    0.000    0.123    0.000 crs.py:42(_safe_pj_transform)
...
        1    0.000    0.000    0.003    0.003 transformer.py:471(from_crs)
        1    0.000    0.000    0.003    0.003 transformer.py:298(__init__)
        1    0.000    0.000    0.003    0.003 transformer.py:91(__call__)
...
        1    0.003    0.003    0.003    0.003 {pyproj._transformer.from_crs}
```
Is there any chance Cartopy could take care of caching transformers in a similar manner?

### PR DESCRIPTION
**Pull request by greglucas**
This adds a cache mechanism to creating Transformer objects, which
can be slow when called frequently. Additionally, this requires
adding attributes to the Mercator creation as the x/y limits are
created in the initializer which uses the cache/hash function.

closes #1915

### CODE REVIEW

**Comment by Bob131** [comment]
Yep, this seems to solve the issue I was hitting.

Here's the benchmark I was using, btw. I wrote it thinking the problem was due to transforming polygon points, but tweaking things it seems the important bits are the grid line labels.

```py
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.patches import Polygon

import cartopy.crs as ccrs


class PolygonAnimation:
    params = [
        ( 8, 128),
        (50, 200)
    ]
    param_names = ['n_points', 'n_frames']

    def setup(self, n_points, n_frames):
        self.polygon_points = \
            np.array([[np.cos(x), np.sin(x)]
                      for x in np.linspace(0, 2 * np.pi, n_points)]) \
                          * 180 / np.pi
        self.proj = ccrs.PlateCarree()
        fig, ax = plt.subplots(subplot_kw=dict(projection=self.proj))
        ax.set_global()
        ax.gridlines(crs=self.proj, draw_labels={'left': 'y'}, x_inline=True)
        self.figure = fig
        self.polygon = ax.add_patch(Polygon(self.polygon_points,
                                            transform=self.proj.as_geodetic()))
        self.animation = FuncAnimation(fig, self.update,
                                       frames=np.linspace(0, 360, n_frames),
                                       blit=True)

    def update(self, frame):
        self.polygon.set_xy(self.polygon_points + (frame, 0))
        return self.polygon,

    def time_draw(self, n_points, n_frames):
        self.animation.save('/tmp/cartopy-bench.gif')
```

```
➜  cartopy git:(5540d799) ✗  asv --config benchmarks/asv.conf.json run -b polygon_animation 'HEAD~2..HEAD'
· Creating environments
· Discovering benchmarks
·· Uninstalling from virtualenv-py3.10-fiona-matplotlib-numpy-pykdtree-pyproj-scipy
·· Installing 5540d799 into virtualenv-py3.10-fiona-matplotlib-numpy-pykdtree-pyproj-scipy.
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[  0.00%] · For cartopy commit 5540d799:
[  0.00%] ·· Benchmarking virtualenv-py3.10-fiona-matplotlib-numpy-pykdtree-pyproj-scipy
[ 25.00%] ··· Running (polygon_animation.PolygonAnimation.time_draw--).
[ 50.00%] ··· polygon_animation.PolygonAnimation.time_draw                                                                          ok[ 50.00%] ··· ========== ============ ============
              --                  n_frames        
              ---------- -------------------------
               n_points       50          200     
              ========== ============ ============
                  8       2.46±0.01s   9.10±0.01s 
                 128      2.74±0.09s   10.2±0.04s 
              ========== ============ ============

[ 50.00%] · For cartopy commit 313f02f3 <master>:
[ 50.00%] ·· Building for virtualenv-py3.10-fiona-matplotlib-numpy-pykdtree-pyproj-scipy.
[ 50.00%] ·· Benchmarking virtualenv-py3.10-fiona-matplotlib-numpy-pykdtree-pyproj-scipy
[ 75.00%] ··· Running (polygon_animation.PolygonAnimation.time_draw--).
[100.00%] ··· polygon_animation.PolygonAnimation.time_draw                                                                          ok[100.00%] ··· ========== ============ ============
              --                  n_frames        
              ---------- -------------------------
               n_points       50          200     
              ========== ============ ============
                  8       7.13±0.03s   28.6±0.06s 
                 128       7.39±0s     29.5±0.06s 
              ========== ============ ============
```

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
@greglucas Could we instead make our own `get_crs_from_transformer` (or something) which uses `lru_cache` that we call? I’d really like to avoid monkeypatching pyproj, which can impact people who are using pyproj outside of cartopy within the same program.

**Comment by dopplershift** [comment]
To be clear, something like:
```python
@lru_cache
def get_transformer_from_crs(crs):
    return Transformer.from_crs(crs)
```

**Comment by greglucas** [comment]
Yep, good suggestion. Should be updated on both branches now.

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
