### PR TITLE
added savefig examples to cartopy matplotlib intro

### PR DESCRIPTION
**Pull request by corinnebosley**
Closes https://github.com/SciTools/cartopy/issues/922 (maybe; there is an extra bit about a link to something from something which I don't follow at all, and this PR does not address that.)

### CODE REVIEW

**Comment by corinnebosley** [comment]
I know that this isn't done yet, I still need to actually link that sentence up to something.  Where do I have to put the link in?

**Comment by pp-mo** [comment]
> Where do I have to put the link in?

Did you just mean to get the `:meth:'~matplotlib.pyplot.savefig!'` working ?
I think that is enabled by [this line](https://github.com/SciTools/cartopy/blob/98423a4576b4f9574cb04860a39eb49fc33366e9/docs/source/conf.py#L327) and should already be working.
Build the docs + see if it works ?

**Comment by corinnebosley** [comment]
@pp-mo I've added the stickler yaml, although it probably needs some work. We're getting there though...

**Comment by corinnebosley** [comment]
@pp-mo You happy with this change yet?

**Comment by dopplershift** [comment]
Did you mean to close this?

**Comment by dopplershift** [comment]
I see now, closed in favor of #971.

**Comment by corinnebosley** [comment]
@dopplershift Yeah, had some rebase nightmares.  Thought it was probably best to just start again...

**Pull request closed without merging**
