### PR TITLE
Update some web tile test images.

### PR DESCRIPTION
**Pull request by QuLogic**
Honestly, I can barely see the difference.

### CODE REVIEW

**Comment by ajdawson** [comment]
Can you rebase this to pick up the Travis changes from your other PR and we'll see how we get on.

**Comment by QuLogic** [comment]
Voilà.

**Comment by ajdawson** [comment]
OK I don't really understand what the difference is or what caused it, but I'm content that this achieves peace and harmony re testing so I'm in...

**Comment by QuLogic** [comment]
They're some web tiles, so I _think_ it's something going on on whatever server from which they get loaded.

**Pull request merged**
