### PR TITLE
Backported fixes for 0.13.1

### PR DESCRIPTION
**Pull request by rhattersley**
Backport of #685 to v0.13.x

### CODE REVIEW

**Comment by pelson** [comment]
Looks like we should also backport #675.

**Comment by rhattersley** [comment]
> Looks like we should also backport #675.

Want me to do that in this PR?

**Comment by pelson** [comment]
> Want me to do that in this PR?

I'm ok with that.

**Comment by pelson** [comment]
P.S. I'm also happy for you to self-merge simple backports (perhaps more cautiously if there were merge conflicts)

**Comment by QuLogic** [comment]
Ping? Web tiles is making CI... difficult...

**Comment by QuLogic** [comment]
Don't forget to drop the web tiles changes here; should release after this?

**Comment by gauteh** [comment]
hi. the shapely bug keeps biting me, would be great with a .13.1 release which includes that fix.

**Comment by pelson** [comment]
@rhattersley - would you mind brining this back to life? We have merge conflicts.

**Comment by rhattersley** [comment]
@pelson - updated.

The conflict was with the webtiles image in #694 and 46d31c9658f2a8c1917a3d0d4a3b3ca608b29cde, so I've just dropped the image update from this PR.

**Comment by QuLogic** [comment]
So, release then?

**Comment by rhattersley** [comment]
> So, release then?

:+1:

**Comment by rhattersley** [comment]
#705 should let us do the release.

**Pull request merged**
