### PR TITLE
Updated to v0.13.dev1.

### PR DESCRIPTION
**Pull request by pelson**
The change from 0.12.x to 0.13.dev1 is in accordance with PEP440. It should make no difference to development in practice - the branches will still be named v0.12.x/0.13.x etc.

### CODE REVIEW

**Comment by QuLogic** [comment]
You can also use `dev0` if you really really want to signify it's not a release.

**Comment by pelson** [comment]
Or just drop the number altogether: https://www.python.org/dev/peps/pep-0440/#implicit-development-release-number

**Comment by QuLogic** [comment]
Yep, but we've seen that pip still warns about it when you don't have one.

**Comment by pelson** [comment]
Fixed. Thanks @QuLogic

**Comment by QuLogic** [comment]
You can get a :+1: from me, if you're looking for one, except the commit message is inconsistent.

**Comment by pelson** [comment]
> You can get a :+1: from me, if you're looking for one

I am. :wink:

**Pull request merged**
