### PR TITLE
Doc switch to pydata theme and reorganization

### PR DESCRIPTION
**Pull request by greglucas**
## Rationale

There are quite a few issues in the tracker open about documentation and organization. https://github.com/SciTools/cartopy/search?q=documentation&type=Issues
One such issue: https://github.com/SciTools/cartopy/issues/1510

This update keeps most of the content from the previous site, but reorganizes it with the pydata theme and uses more general :toctree: calls for an API reference rather than inline descriptions.

## Implications

Currently, there is not a version_switcher in the pydata theme. I did rework the nav-item's and could insert it to look like this:

But, that would involve overwriting the main pydata theme navbar and potentially getting out of sync with it.

### CODE REVIEW

**Comment by QuLogic** [comment]
This looks fairly nice, though I have really looked at it in depth.

**Comment by greglucas** [comment]
ping: @jypeter and @stefraynaud
You both had suggestions/comments on the linked documentation issue. Feel free to review this and suggest changes.

**Comment by stefraynaud** [comment]
@greglucas This is a huge improvement the doc!

Minor suggestions :
- I'm not sure the "Getting involed" block is at the right place. Maybe an alternative is to merge the home page with the current Readme file, and include it in the index page with `.. include::` directive.
- Please add the module names in the title of the API sections.

Nice work.

@jypeter you can have a look to the doc by clicking on the "Show all checks" link of the CI status at the Bottom of this page, then on the "Details" link in front of "ci/circleci: docs-python3 artifact".

**Comment by greglucas** [comment]
Excellent, thank you for the feedback!

1. I agree, the entire landing page feels a bit awkward at the moment and "Getting Involved" really isn't important to a first-time user just arriving at the docs. The current README has some circular language pointing to the docs and extra copyright/licensing things that I think should get pushed back a page. Getting Started may be a better landing page, but more verbose. I'll give this some thought and try to reorg it a bit (so far I just tried to re-layout the current content, not rewrite content).

2. Where do you want to see module names? In the API reference page itself, or the subsections from there? Something like: `Matplotlib interface (cartopy.mpl)`? I was trying to loosely follow [numpy](https://numpy.org/devdocs/reference/index.html) and [pandas](https://pandas.pydata.org/docs/reference/index.html). It looks like numpy includes some, pandas doesn't. We also have quite a few nested layers of modules it seems like, so I'm not real clear on where to draw the line for each one. (Also note, currently the documentation for each *class* page does include the full [module path](https://2358-5282596-gh.circle-artifacts.com/0/docs/build/html/reference/generated/cartopy.mpl.ticker.LongitudeFormatter.html#cartopy.mpl.ticker.LongitudeFormatter).

**Comment by stefraynaud** [comment]
OK.
As for the module names, the case of numpy is special since almost everything is available under `numpy.`.
In the case of pandas, the module name is not shown in the module title, however the module/section content show full declaration paths so it make it clear in which submodule we are.
For instance, it is not clear on the overview page that we are in the in the `cartopy.mpl` module whereas this becomes clear in the item page: 
* overview : https://2358-5282596-gh.circle-artifacts.com/0/docs/build/html/reference/matplotlib.html#gridlines-and-ticks 
* item : https://2358-5282596-gh.circle-artifacts.com/0/docs/build/html/reference/generated/cartopy.mpl.geoaxes.GeoAxes.html#cartopy.mpl.geoaxes.GeoAxes

**Comment by greglucas** [comment]
Thanks @stefraynaud, that makes sense. I moved some of those to the section headers (`cartopy.mpl`), but others I just more explicitly wrote out in the subsection instead (`geoaxes.Geoaxes`). I'm not sure how we should deal with the doubly nested structures like `cartopy.io.shapereader`, would you want to see the full `io.shapereader.ShapeReader` path, or is it obvious enough as is? Let me know what you think of this new version.

**Comment by jypeter** [comment]
Thanks @greglucas and @stefraynaud !

**Comment by stefraynaud** [comment]
Its seems that this docstring code is not well processed by sphinx:

````
        Keyword Parameters
        ------------------
````

**Comment by greglucas** [comment]
That should just be under the `Parameters` section. I've moved that now.

I think there are a lot of other fixes like updating types/intersphinx references better, but I'd rather hold off on those for separate PRs. This is a major overhaul already and I'd like to keep it somewhat self-contained to only updating the documentation format/structure for now.

**Comment by greglucas** [comment]
Plugging this PR for a review as well, I think it is a major improvement to the doc situation.

Rendered version: https://2692-5282596-gh.circle-artifacts.com/0/docs/build/html/index.html

**Comment by QuLogic** [comment]
It looks like the What's new for 0.19 is missing from the index?

**Comment by QuLogic** [comment]
The extra macOS instructions in the Required Dependencies section appear to be not indented like they were before, but really, they should be code styled.

**Comment by greglucas** [comment]
Thanks for pointing those out! I updated the MacOS extra instructions to follow the same style as above and added in the v0.19 release notes.

**Review by QuLogic — APPROVED** [review]

**Comment by greglucas** [comment]
I'm going to merge this so I don't have to keep rebasing. We can start making smaller doc PRs on top of this now. Thanks for the feedback and improvements, everyone!

**Pull request merged**
