### PR TITLE
Reinstate missing renderer argument in `GeoAxes._preprocess_draw`

### LINKED ISSUE #2464: Cartopy 0.24 throws a `TypeError` when saving with `bbox_inches="tight"`
### Description

Crash when plotting with `bbox_inches="tight"` in cartopy v0.24.0. This issue does not occur in v0.23, and I've traced it down to 454567a2c8876f90969617be6fe4fd053f5e5e21 as the cause.

#### Code to reproduce

https://github.com/MetOffice/CSET/blob/adad8cc2341607e9fcfe796271368732201b75fc/tests/operators/test_plots.py#L74-L80

which runs

https://github.com/MetOffice/CSET/blob/adad8cc2341607e9fcfe796271368732201b75fc/src/CSET/operators/plot.py#L187-L279

#### Traceback

```
tests/operators/test_plots.py::test_spatial_pcolormesh_plot FAILED                                                                                                     [100%]

================================================================================== FAILURES ==================================================================================
________________________________________________________________________ test_spatial_pcolormesh_plot ________________________________________________________________________

cube = <iris 'Cube' of air_temperature / (K) (time: 3; grid_latitude: 17; grid_longitude: 13)>
tmp_working_dir = PosixPath('/var/tmp/pytest-of-jfrost/pytest-889/test_spatial_pcolormesh_plot0')

    def test_spatial_pcolormesh_plot(cube, tmp_working_dir):
        """Plot spatial pcolormesh plot of instant air temp."""
        # Remove realization coord to increase coverage, and as its not needed.
        cube.remove_coord("realization")
        cube_2d = cube.slices_over("time").next()
>       plot.spatial_pcolormesh_plot(cube_2d, filename="plot")

/net/home/h02/jfrost/Projects/CSET/tests/operators/test_plots.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/net/home/h02/jfrost/Projects/CSET/src/CSET/operators/plot.py:894: in spatial_pcolormesh_plot
    _spatial_plot("pcolormesh", cube, filename, sequence_coordinate, stamp_coordinate)
/net/home/h02/jfrost/Projects/CSET/src/CSET/operators/plot.py:783: in _spatial_plot
    plotting_func(
/net/home/h02/jfrost/Projects/CSET/src/CSET/operators/plot.py:277: in _plot_and_save_spatial_plot
    fig.savefig(filename, bbox_inches="tight", dpi=_get_plot_resolution())
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/figure.py:3395: in savefig
    self.canvas.print_figure(fname, **kwargs)
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/backend_bases.py:2175: in print_figure
    self.figure.draw(renderer)
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/artist.py:95: in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/artist.py:72: in draw_wrapper
    return draw(artist, renderer)
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/figure.py:3162: in draw
    mimage._draw_list_compositing_images(
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/image.py:132: in _draw_list_compositing_images
    a.draw(renderer)
/tmp/persistent/conda/envs/cset-test/lib/python3.12/site-packages/matplotlib/artist.py:72: in draw_wrapper
    return draw(artist, renderer)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_GeoAxesPatched: title={'center': 'Untitled | 2022-09-21 03:00:00'}>, renderer = <matplotlib.backends.backend_agg.RendererAgg object at 0x2b336e9530e0>, kwargs = {}

    @matplotlib.artist.allow_rasterization
    def draw(self, renderer=None, **kwargs):
        """
        Extend the standard behaviour of :func:`matplotlib.axes.Axes.draw`.
    
        Draw image factory results before invoking standard Matplotlib drawing.
        A global range is used if no limits have yet been set.
        """
        # Shared processing steps
>       self._draw_preprocess()
E       TypeError: _GeoAxesPatched._draw_preprocess() missing 1 required positional argument: 'renderer'

/net/home/h02/jfrost/Projects/cartopy/lib/cartopy/mpl/geoaxes.py:494: TypeError
========================================================================== short test summary info ===========================================================================
FAILED tests/operators/test_plots.py::test_spatial_pcolormesh_plot - TypeError: _GeoAxesPatched._draw_preprocess() missing 1 required positional argument: 'renderer'

```

<details>
 <summary>Full environment definition</summary>

### Operating system
Linux (RHEL 7)

### Cartopy version
0.24.0

### Conda list

https://github.com/MetOffice/CSET/blob/adad8cc2341607e9fcfe796271368732201b75fc/requirements/locks/py312-lock-linux-64.txt

</details>

### PR DESCRIPTION
**Pull request by jfrost-mo**
## Rationale

Fixes #2464.

I've reimplemented what I believe was the intent of 454567a2c8876f90969617be6fe4fd053f5e5e21 from PR #2424, in such a way that it no longer changes the method signature in a problematic way.

## Implications

This should now be fully compatible with existing code.

I have manually tested this change however I haven't added any automatic tests. If one is needed then I'm happy to create one.

### CODE REVIEW

**Comment by rcomer** [comment]
Thanks for your willingness to contribute @jfrost-mo!

What Iris version did you test this with?  My understanding of the problem is that it happens when `get_tight_bbox` or `draw` calls Iris’s patched `_draw_preprocess` without the parameter (which the patched method expects), so I would expect any fix to be in the callers.

However, since the problem is already fixed in the Iris release candidate, I’m not sure it makes sense to also fix it here.

**Comment by jfrost-mo** [comment]
This is failing on Iris 3.10.0, specifically https://conda.anaconda.org/conda-forge/noarch/iris-3.10.0-pyha770c72_1.conda#b7212cd8247ce909631fdcb77015914a

**Comment by rcomer** [comment]
Right, so when you tested this Cartopy branch, was that definitely with Iris 3.10?  I think there was some sort of glitch that meant conda-forge users were getting Iris 3.11rc without deliberately selecting it.
https://github.com/SciTools/iris/discussions/5571#discussioncomment-11090031

**Comment by jfrost-mo** [comment]
I was using the given conda lockfiles, including hashes, so unless you somehow managed to get around that it should have been 3.10.0.

**Comment by jfrost-mo** [comment]
This has been resolved in iris 3.11.0rc0.

**Pull request closed without merging**
