### PR TITLE
Workaround for mutable geometry caching

### LINKED ISSUE #682: cartopy coastlines issue with shapely 1.5.13
With shapely 1.5.13 the following cartopy example generates an incomplete figure:

```
import os
import matplotlib.pyplot as plt

from cartopy import config
import cartopy.crs as ccrs


fig = plt.figure(figsize=(8, 12))

# get the path of the file. It can be found in the repo data directory.
fname = os.path.join(config["repo_data_dir"],
                     'raster', 'sample', 'Miriam.A2012270.2050.2km.jpg'
                     )
img_extent = (-120.67660000000001, -106.32104523100001, 13.2301484511245, 30.766899999999502)
img = plt.imread(fname)

ax = plt.axes(projection=ccrs.PlateCarree())
plt.title('Hurricane Miriam from the Aqua/MODIS satellite\n'
          '2012 09/26/2012 20:50 UTC')

# set a margin around the data
ax.set_xmargin(0.05)
ax.set_ymargin(0.10)

# add the image. Because this image was a tif, the "origin" of the image is in the
# upper left corner
ax.imshow(img, origin='upper', extent=img_extent, transform=ccrs.PlateCarree())
ax.coastlines(resolution='50m', color='black', linewidth=1)

# mark a known place to help us geo-locate ourselves
ax.plot(-117.1625, 32.715, 'bo', markersize=7, transform=ccrs.Geodetic())
ax.text(-117, 33, 'San Diego', transform=ccrs.Geodetic())

plt.show()
```

I think the error comes from the ax.coastlines line. The error goes away by reverting back to shapely 1.5.12. 
Otherwise I'm using cartopy 0.13.0 and matplotlib 1.4.3 on CentOS 6.
The code comes from http://scitools.org.uk/cartopy/docs/latest/matplotlib/advanced_plotting.html.

Thought this might be useful to know.

### PR DESCRIPTION
**Pull request by rhattersley**
Fixes #682.

### CODE REVIEW

**Comment by florian-wagner** [comment]
Fixes my problem. Thanks a lot.

**Comment by pelson** [comment]
@SciTools/cartopy-devs - we could do with figuring out whether we should create a new release, or issue a patch release for this change...

**Comment by rhattersley** [comment]
Depends how quickly a 0.14 can be released - looks like there's a lot of stuff [still to do](https://github.com/SciTools/cartopy/milestones/0.14). In which case, back-porting to v0.13 would be doubly useful.

**Comment by ajdawson** [comment]
I'd do a patch release of v0.13.1 with this change applied if possible.

**Pull request merged**
