### PR TITLE
Remove the use of shapely.speedups.enable() thanks to https://github.com/Toblerity/Shapely/pull/252

### PR DESCRIPTION
**Pull request by pelson**
xref:  https://github.com/Toblerity/Shapely/pull/252

In general, it is good to follow the principle of no side-effects upon import 😉

### CODE REVIEW

**Comment by QuLogic** [comment]
It's a new year...

**Comment by pelson** [comment]
:cry: - I've wanted to setup a CI bot for this for so long. Maybe now is the time...

**Comment by QuLogic** [comment]
So that was probably caused by some other PRs being merged; I fixed it in #994.

**Comment by pelson** [comment]
Merge when happy. 👍

**Pull request merged**
