### PR TITLE
Backports for 0.20.x

### PR DESCRIPTION
**Pull request by dopplershift**
Ok, grabbing some bug fixes from 0.20.3 milestone:

* #2056 
* #2057
* #2058
* #1989

This had a few conflicts to take care of.

### CODE REVIEW

**Comment by dopplershift** [comment]
Do we want to make a 0.20.3 or a 0.20.2.post1?

**Review by greglucas — APPROVED** [review]
I'd vote for a `.post1` release here just to unbreak the pip installs. There might need to be a few other backports and conflicts to mess around with if we try to do a new minor release that I'm not sure are worthwhile here...

**Comment by QuLogic** [comment]
It's just that we have broken tests now; it might be good to backport those fixes as well...

**Comment by dopplershift** [comment]
I don't understand. One fails with `test_examples::test_contour_label` and the other `test_crs.py::test_igh_[ocean|land]`.

**Comment by dopplershift** [comment]
All versions failing (at least last time) were Matplotlib 3.5.2, which is also passing on other runs. 😬 I also note now that ubuntu 3.8 failed a test after I added my debug output, and it didn't fail last time. Something non-deterministic is going on it seems...

**Comment by dopplershift** [comment]
Oh swell, re-running finally fixed one of them.

**Comment by dopplershift** [comment]
I figured it out: PROJ 8 vs. 9 apparently triggers a few minor image changes. There's an ambiguity in solving where you can either get either PROJ 9 and owslib 0.25 or PROJ 8 and owslib 0.26.

I don't think I can express just how much I hate software right now. (╯°□°）╯︵ ┻━┻

**Comment by greglucas** [comment]
You are far braver than I to venture into the backporting world ;) I would have taken the easy way out and pushed a `.post1` 😂

**Comment by dopplershift** [comment]
Honestly, the backports have been easy. Figuring out why CI is failing is...so annoying.

I share @QuLogic's unease with cutting a release from failing tests...

**Comment by dopplershift** [comment]
So apparently it's actually a change produced by PROJ 9.0.1 vs. 9.0.0. On Python 3.7, we can only install PROJ 9.0.0 because the only versions of pyproj that have been recompiled for PROJ 9.0.1 don't support Python 3.7. 😱 

Therefore for this branch (and I think it should stay here) I included the PROJ version in the check for an appropriate tolerance.

**Comment by QuLogic** [comment]
Strange that didn't come up in #2051.

**Comment by dopplershift** [comment]
@QuLogic Well, they're the tests I fixed in #2058, but I assumed it was due to matplotlib. The tests were failing in #2056, we just didn't worry about fixing them there.

**Comment by dopplershift** [comment]
:tada: @greglucas @QuLogic 

Not sure why it finally passed, but it did. I've been unable to reproduce the series of failures locally in a VM.

Regardless, if someone can merge we can cut 0.20.3!

**Comment by greglucas** [comment]
Lets hope it stays that way once merged too :)

@dopplershift, go ahead and make the release. Thanks for doing all that work with CI and backporting!

**Comment by dopplershift** [comment]
Note to self: backporting like this makes the autogenerated release notes basically useless.

**Pull request merged**
